import assert from "node:assert/strict";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { buildDirectTargetList, createDirectTargetListBuilderId, rankDirectTargets, renderDirectTargetListCsv, renderDirectTargetListMarkdown, scoreDirectTarget, summariseDirectTargetList, type DirectTargetListInput } from "../src/direct-target-list-builder.js";
import { runDirectTargetListBuilderCli } from "../src/direct-target-list-builder-cli.js";
const root = process.cwd(); const path = join(root, "examples", "direct-target-list-builder-input.json"); const load = () => JSON.parse(readFileSync(path, "utf8")) as DirectTargetListInput;

test("ready offer and approved valid target produce review-ready ranked list", () => { const result = buildDirectTargetList(load()); assert.equal(result.commercial_status, "target_list_ready_for_gareth_review"); assert.equal(result.input_target_count, 4); assert.equal(result.accepted_target_count, 4); assert.ok(result.top_priority_targets.length > 0); assert.ok(result.target_summary.high_priority > 0); assert.ok(result.recommended_next_steps.length > 0); assert.equal(result.gareth_approval_required_before_contact, true); assert.equal(result.no_automatic_contact, true); assert.equal(result.no_scraping_performed, true); });
test("missing offer readiness and empty target list hold safely", () => { const missing = load(); missing.offer_pack_result = {}; assert.equal(buildDirectTargetList(missing).commercial_status, "target_list_hold"); const empty = load(); empty.targets = []; assert.equal(buildDirectTargetList(empty).commercial_status, "target_list_hold"); });
test("scores and ranking are deterministic across priority bands", () => { const high = scoreDirectTarget(load().targets[0]!); assert.equal(high.pilot_fit_score, 100); assert.equal(high.priority_band, "high_priority"); assert.deepEqual(high, scoreDirectTarget(load().targets[0]!)); const low = scoreDirectTarget({ target_name: "Example Low Fit System", target_category: "other", agent_system_relevance: "medium", governance_need: "low", integration_complexity: "high" }); assert.ok(low.priority_band === "low_priority" || low.priority_band === "not_recommended"); const ranked = rankDirectTargets([low, high]); assert.equal(ranked[0]?.target_name, high.target_name); });
test("missing and contact-like names are rejected", () => { for (const input of [{ target_category: "other" }, { target_name: "person@example.test", target_category: "other" }]) { const target = scoreDirectTarget(input); assert.equal(target.rejection_reason, "missing_or_unsafe_target_name"); assert.equal(target.contact_readiness, "rejected"); } });
test("requested prohibited capabilities block the list while outputs stay false", () => { const input = load(); input.safety_flags = { network_lookup_enabled: true }; assert.equal(buildDirectTargetList(input).commercial_status, "target_list_blocked"); const result = buildDirectTargetList(load()); for (const value of [result, summariseDirectTargetList(result)]) for (const key of ["private_data_included", "network_lookup_performed", "external_lookup_performed", "public_api_enabled", "tracking_triggered", "analytics_triggered", "payment_or_fee_triggered", "billing_triggered", "settlement_triggered", "machine_to_machine_fee_triggered", "action_executed", "email_sent", "message_sent", "scraped", "deployed", "published"] as const) assert.equal(value[key], false, key); });
test("Markdown and CSV contain bounded planning data", () => { const result = buildDirectTargetList(load()); const markdown = renderDirectTargetListMarkdown(result); for (const text of ["Direct Target List Builder", "Commercial Status", "Top Priority Targets", "Contact Policy", "Gareth Approval Gate", "No scraping, searching, contact, email, or message has occurred"]) assert.match(markdown, new RegExp(text, "i")); const csv = renderDirectTargetListCsv(result); assert.match(csv, /^target_id,target_name,target_category,likely_buyer_role,pilot_fit_score,priority_band,risk_level,contact_readiness,gareth_approval_status,recommended_message_angle,next_manual_action/m); assert.doesNotMatch(csv, /@|https?:\/\/|api_key|payment link|tracking_id/i); });
test("private fields and arbitrary descriptions never enter any output", () => { const input = load(); Object.assign(input.targets[0]!, { customer_name: "Private Person", customer_email: "private@example.test", company_name: "Secret Company", personal_email: "personal@example.test", direct_email: "direct@example.test", phone_number: "01234", bank_account: "111", card_number: "222", wallet_address: "333", api_key: "secret-key", access_token: "secret-token", private_document_text: "private text", invoice_number: "INV-PRIVATE", contract_text: "secret contract", real_agent_endpoint: "private endpoint", real_url: "private url", real_email_content: "secret email", linkedin_profile_url: "private profile", personal_address: "private address", target_description: "do-not-copy-description", notes: "do-not-copy-notes" }); const result = buildDirectTargetList(input); const output = [JSON.stringify(result), JSON.stringify(summariseDirectTargetList(result)), renderDirectTargetListMarkdown(result), renderDirectTargetListCsv(result)].join("\n"); for (const value of ["Private Person", "private@example.test", "Secret Company", "secret-key", "INV-PRIVATE", "do-not-copy-description", "do-not-copy-notes", "customer_name", "api_key"]) assert.doesNotMatch(output, new RegExp(value, "i")); });
test("CLI supports JSON Markdown CSV and returns safe validation errors", () => { for (const [flag, pattern] of [["--pretty", /target_list_ready_for_gareth_review/], ["--markdown", /Direct Target List Builder/], ["--csv", /^target_id,target_name/m]] as const) { const out: string[] = []; assert.equal(runDirectTargetListBuilderCli([path, flag], { stdout: value => out.push(value), stderr: () => undefined }), 0); assert.match(out[0] ?? "", pattern); } const malformed = join(root, "target-list-malformed.tmp.json"), noOffer = join(root, "target-list-no-offer.tmp.json"), noTargets = join(root, "target-list-no-targets.tmp.json"), empty = join(root, "target-list-empty.tmp.json"); writeFileSync(malformed, "{bad"); writeFileSync(noOffer, JSON.stringify({ source_id: "x", targets: [{}], created_at: "2026-01-01T00:00:00Z" })); writeFileSync(noTargets, JSON.stringify({ source_id: "x", offer_pack_result: {}, created_at: "2026-01-01T00:00:00Z" })); writeFileSync(empty, JSON.stringify({ source_id: "x", offer_pack_result: {}, targets: [], created_at: "2026-01-01T00:00:00Z" })); const cases: Array<[string[], string]> = [[[], "MISSING_INPUT_FILE"], [[join(root, "absent-target-list.json")], "INPUT_FILE_UNREADABLE"], [[malformed], "INVALID_JSON"], [[noOffer], "INVALID_INPUT"], [[noTargets], "INVALID_INPUT"], [[empty], "EMPTY_TARGETS"]]; try { for (const [args, code] of cases) { const errors: string[] = []; assert.equal(runDirectTargetListBuilderCli(args, { stdout: () => undefined, stderr: value => errors.push(value) }), 1); const parsed = JSON.parse(errors[0] ?? "{}") as { error?: { code?: string }; email_sent?: boolean; scraped?: boolean }; assert.equal(parsed.error?.code, code); assert.equal(parsed.email_sent, false); assert.equal(parsed.scraped, false); } } finally { for (const file of [malformed, noOffer, noTargets, empty]) rmSync(file, { force: true }); } });
test("documentation and placeholder examples exist", () => { for (const file of ["docs/direct-target-list-builder.md", "examples/direct-target-list-builder-input.json", "examples/direct-target-list-builder-output.json", "examples/direct-target-list-builder-markdown.md", "examples/direct-target-list-builder.csv", "examples/direct-target-list-builder-empty-targets.json", "examples/direct-target-list-builder-private-data-rejected.json", "examples/direct-target-list-builder-live-access-blocked.json"]) assert.equal(existsSync(join(root, file)), true, file); for (const file of ["examples/direct-target-list-builder-input.json", "examples/direct-target-list-builder-output.json", "examples/direct-target-list-builder-markdown.md", "examples/direct-target-list-builder.csv"]) assert.doesNotMatch(readFileSync(join(root, file), "utf8"), /@|https?:\/\//); });
test("builder IDs are deterministic and pseudonymous", () => { const id = createDirectTargetListBuilderId("private@example.test"); assert.equal(id, createDirectTargetListBuilderId("private@example.test")); assert.doesNotMatch(id, /private|example/); });
