import assert from "node:assert/strict";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { createDirectAgentSystemPilotOfferPack, createDirectAgentSystemPilotOfferPackId, renderDirectAgentSystemPilotOfferJson, renderDirectAgentSystemPilotOfferPackMarkdown, renderDirectPilotContactMessage, summariseDirectAgentSystemPilotOfferPack, type DirectAgentSystemPilotOfferPackInput } from "../src/direct-agent-system-pilot-offer-pack.js";
import { runDirectAgentSystemPilotOfferPackCli } from "../src/direct-agent-system-pilot-offer-pack-cli.js";
const root = process.cwd(); const inputPath = join(root, "examples", "direct-agent-system-pilot-offer-pack-input.json");
const load = () => JSON.parse(readFileSync(inputPath, "utf8")) as DirectAgentSystemPilotOfferPackInput;

test("approved record creates a complete draft private pilot offer", () => { const pack = createDirectAgentSystemPilotOfferPack(load()); assert.equal(pack.commercial_status, "draft_private_pilot_offer_ready"); for (const key of ["offer_positioning", "buyer_problem", "target_audience", "target_system_profile", "direct_pilot_offer", "pilot_pricing_options", "qualification_questions", "machine_readable_offer", "human_readable_brief", "direct_contact_message", "technical_invitation_message", "what_remains_disabled"] as const) assert.ok(pack[key], key); assert.equal(pack.gareth_approval_required_before_sending, true); });
test("unapproved record holds commercial readiness", () => { const input = load(); input.approval_record_result.approval_status = "held"; assert.equal(createDirectAgentSystemPilotOfferPack(input).commercial_status, "hold_for_gareth_approval"); });
test("IDs are deterministic and contain no source text", () => { const a = createDirectAgentSystemPilotOfferPackId("private@example.test"); assert.equal(a, createDirectAgentSystemPilotOfferPackId("private@example.test")); assert.doesNotMatch(a, /private|example/); });
test("all non-sending and live safety values remain false", () => { const pack = createDirectAgentSystemPilotOfferPack(load()); for (const value of [pack, summariseDirectAgentSystemPilotOfferPack(pack)]) for (const key of ["private_data_included", "network_lookup_performed", "external_lookup_performed", "public_api_enabled", "tracking_triggered", "analytics_triggered", "payment_or_fee_triggered", "billing_triggered", "settlement_triggered", "machine_to_machine_fee_triggered", "action_executed", "email_sent", "message_sent", "scraped", "deployed", "published"] as const) assert.equal(value[key], false, key); });
test("renderers produce bounded offer material", () => { const pack = createDirectAgentSystemPilotOfferPack(load()); const markdown = renderDirectAgentSystemPilotOfferPackMarkdown(pack); for (const value of ["Direct Agent/System Pilot Offer Pack", "Product Positioning", "Private Pilot Offer", "Direct Contact Message", "What Remains Disabled", "nothing has been sent"]) assert.match(markdown, new RegExp(value, "i")); const offer = JSON.parse(renderDirectAgentSystemPilotOfferJson(pack)) as Record<string, unknown>; for (const key of ["offer_type", "product_name", "pilot_scope", "disabled_capabilities", "required_approvals"]) assert.ok(key in offer, key); assert.match(renderDirectPilotContactMessage(pack), /Agent Trust Gate™.*private pilot/i); });
test("private input values never enter pack or renderers", () => { const input = load(); Object.assign(input, { customer_name: "Private Person", customer_email: "private@example.test", company_name: "Secret Company", bank_account: "111", card_number: "222", wallet_address: "333", api_key: "secret-key", access_token: "secret-token", private_document_text: "private text", invoice_number: "INV-PRIVATE", contract_text: "secret contract", real_agent_endpoint: "https://private.invalid", real_url: "https://private.invalid", real_email_content: "secret email" }); const pack = createDirectAgentSystemPilotOfferPack(input); const output = [JSON.stringify(pack), renderDirectAgentSystemPilotOfferPackMarkdown(pack), renderDirectAgentSystemPilotOfferJson(pack), renderDirectPilotContactMessage(pack)].join("\n"); for (const value of ["Private Person", "private@example.test", "Secret Company", "secret-key", "secret-token", "INV-PRIVATE", "private.invalid", "secret email", "customer_name", "api_key"]) assert.doesNotMatch(output, new RegExp(value, "i")); });
test("CLI supports JSON Markdown offer JSON and contact-message output", () => { for (const [flag, pattern] of [["--pretty", /draft_private_pilot_offer_ready/], ["--markdown", /Direct Agent\/System Pilot Offer Pack/], ["--offer-json", /private_fake_agent_sandbox_pilot/], ["--contact-message", /Agent Trust Gate™.*private pilot/i]] as const) { const output: string[] = []; assert.equal(runDirectAgentSystemPilotOfferPackCli([inputPath, flag], { stdout: value => output.push(value), stderr: () => undefined }), 0); assert.match(output[0] ?? "", pattern); } });
test("CLI returns safe errors for missing unreadable malformed and incomplete input", () => { const malformed = join(root, "pilot-offer-malformed.tmp.json"), incomplete = join(root, "pilot-offer-incomplete.tmp.json"); writeFileSync(malformed, "{bad"); writeFileSync(incomplete, JSON.stringify({ source_id: "x", created_at: "2026-01-01T00:00:00Z" })); const cases: Array<[string[], string]> = [[[], "MISSING_INPUT_FILE"], [[join(root, "absent-pilot-offer.json")], "INPUT_FILE_UNREADABLE"], [[malformed], "INVALID_JSON"], [[incomplete], "INVALID_INPUT"]]; try { for (const [args, code] of cases) { const errors: string[] = []; assert.equal(runDirectAgentSystemPilotOfferPackCli(args, { stdout: () => undefined, stderr: value => errors.push(value) }), 1); const parsed = JSON.parse(errors[0] ?? "{}") as { error?: { code?: string }; email_sent?: boolean; message_sent?: boolean; scraped?: boolean }; assert.equal(parsed.error?.code, code); assert.equal(parsed.email_sent, false); assert.equal(parsed.message_sent, false); assert.equal(parsed.scraped, false); } } finally { rmSync(malformed, { force: true }); rmSync(incomplete, { force: true }); } });
test("documentation and examples exist", () => { for (const file of ["docs/direct-agent-system-pilot-offer-pack.md", "examples/direct-agent-system-pilot-offer-pack-input.json", "examples/direct-agent-system-pilot-offer-pack-output.json", "examples/direct-agent-system-pilot-offer-pack-markdown.md", "examples/direct-agent-system-pilot-offer-pack-offer-json.json", "examples/direct-agent-system-pilot-offer-pack-contact-message.txt", "examples/direct-agent-system-pilot-offer-pack-private-data-rejected.json", "examples/direct-agent-system-pilot-offer-pack-live-access-blocked.json"]) assert.equal(existsSync(join(root, file)), true, file); });
