import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { buildDirectTargetList, renderDirectTargetListCsv, renderDirectTargetListMarkdown, scoreDirectTarget, summariseDirectTargetList, type DirectTargetInput, type DirectTargetListInput } from "../src/direct-target-list-builder.js";
import { runDirectTargetListBuilderCli } from "../src/direct-target-list-builder-cli.js";
const root = process.cwd(), inputPath = join(root, "examples", "global-direct-target-list-builder-input.json");
const load = () => JSON.parse(readFileSync(inputPath, "utf8")) as DirectTargetListInput;
const target = (overrides: Partial<DirectTargetInput> = {}): DirectTargetInput => ({ target_name: "Example Global Scoring Target", target_category: "ai_agent_platform", agent_system_relevance: "high", governance_need: "high", payment_or_action_risk: "high", evidence_need: "high", integration_complexity: "low", commercial_fit: "high", pilot_budget_likelihood: "high", region: "global", country_or_market: "example_global_market", market_scope: "global", global_category: "agent_platform", likely_language: "multilingual", timezone_region: "global", international_relevance: "high", jurisdiction_contact_caution: "low", gareth_approval_status: "not_reviewed", ...overrides });

test("global fields are accepted and high global priority is deterministic", () => { const scored = scoreDirectTarget(target()); assert.equal(scored.region, "global"); assert.equal(scored.market_scope, "global"); assert.equal(scored.manual_contact_only, true); assert.equal(scored.global_pilot_fit_score, 100); assert.equal(scored.global_priority_band, "global_high_priority"); assert.deepEqual(scored, scoreDirectTarget(target())); });
test("global medium and low priority bands are reachable", () => { const medium = scoreDirectTarget(target({ agent_system_relevance: "high", governance_need: "high", payment_or_action_risk: "medium", evidence_need: "medium", commercial_fit: "medium", pilot_budget_likelihood: "medium", integration_complexity: "medium", market_scope: "regional", international_relevance: "medium", jurisdiction_contact_caution: "medium" })); assert.equal(medium.global_priority_band, "global_medium_priority"); const low = scoreDirectTarget(target({ agent_system_relevance: "medium", governance_need: "medium", payment_or_action_risk: "medium", evidence_need: "medium", commercial_fit: "medium", pilot_budget_likelihood: "low", integration_complexity: "medium", market_scope: "regional", international_relevance: "medium", jurisdiction_contact_caution: "medium" })); assert.equal(low.global_priority_band, "global_low_priority"); });
test("high jurisdiction caution and unknown region lower global score", () => { const lowCaution = scoreDirectTarget(target({ jurisdiction_contact_caution: "low" })); const highCaution = scoreDirectTarget(target({ jurisdiction_contact_caution: "high" })); assert.ok(highCaution.global_pilot_fit_score < lowCaution.global_pilot_fit_score); const known = scoreDirectTarget(target({ region: "global" })); const unknown = scoreDirectTarget(target({ region: "unknown" })); assert.ok(unknown.global_pilot_fit_score < known.global_pilot_fit_score); });
test("global result ranks targets and builds deterministic region summary", () => { const result = buildDirectTargetList(load()); assert.equal(result.global_targeting_enabled, true); assert.equal(result.global_target_count, 8); assert.ok(result.top_global_priority_targets.length > 0); for (let index = 1; index < result.top_global_priority_targets.length; index++) assert.ok(result.top_global_priority_targets[index - 1]!.global_pilot_fit_score >= result.top_global_priority_targets[index]!.global_pilot_fit_score); assert.equal(result.global_region_summary.length, 8); assert.deepEqual(result.global_region_summary.map(item => item.recommended_manual_review_order), [1, 2, 3, 4, 5, 6, 7, 8]); assert.ok(result.jurisdiction_contact_cautions.length > 0); });
test("global manual policies and all safety boundaries are fixed", () => { const result = buildDirectTargetList(load()); assert.equal(result.manual_global_review_required, true); assert.equal(result.gareth_approval_required_before_global_contact, true); assert.match(result.global_contact_policy.join(" "), /no automated global outreach/i); assert.match(result.global_contact_policy.join(" "), /no scraping/i); assert.match(result.global_contact_policy.join(" "), /no mass emailing/i); for (const value of [result, summariseDirectTargetList(result)]) for (const key of ["private_data_included", "network_lookup_performed", "external_lookup_performed", "public_api_enabled", "tracking_triggered", "analytics_triggered", "payment_or_fee_triggered", "billing_triggered", "settlement_triggered", "machine_to_machine_fee_triggered", "action_executed", "email_sent", "message_sent", "scraped", "deployed", "published"] as const) assert.equal(value[key], false, key); });
test("global Markdown and CSV include expanded safe fields", () => { const result = buildDirectTargetList(load()), markdown = renderDirectTargetListMarkdown(result); for (const text of ["Global Direct Target List Builder", "Global Coverage", "Region Summary", "Top Global Priority Targets", "Jurisdiction Contact Cautions", "Manual Global Contact Policy", "Gareth Approval Gate", "No scraping, searching, contact, email, or message has occurred"]) assert.match(markdown, new RegExp(text, "i")); const csv = renderDirectTargetListCsv(result); for (const header of ["region", "country_or_market", "market_scope", "global_pilot_fit_score", "global_priority_band"]) assert.match(csv.split("\n")[0] ?? "", new RegExp(header)); assert.doesNotMatch(csv, /@|https?:\/\/|api_key|payment link|tracking_id|phone_number|personal_address/i); });
test("global private and arbitrary compliance fields are never copied", () => { const input = load(); Object.assign(input.targets[0]!, { customer_name: "Private Person", direct_email: "private@example.test", phone_number: "01234", api_key: "secret-key", real_url: "private-url", personal_address: "private-address", contact_compliance_notes: "do-not-copy-compliance-notes" }); const result = buildDirectTargetList(input), output = [JSON.stringify(result), JSON.stringify(summariseDirectTargetList(result)), renderDirectTargetListMarkdown(result), renderDirectTargetListCsv(result)].join("\n"); for (const value of ["Private Person", "private@example.test", "secret-key", "private-url", "private-address", "do-not-copy-compliance-notes", "customer_name", "direct_email"]) assert.doesNotMatch(output, new RegExp(value, "i")); });
test("global CLI supports JSON Markdown and CSV without external activity", () => { for (const [flag, pattern] of [["--pretty", /"global_targeting_enabled": true/], ["--markdown", /Global Direct Target List Builder/], ["--csv", /global_pilot_fit_score/]] as const) { const out: string[] = []; assert.equal(runDirectTargetListBuilderCli([inputPath, flag], { stdout: value => out.push(value), stderr: () => undefined }), 0); assert.match(out[0] ?? "", pattern); } });
test("global docs and placeholder-only examples exist", () => { const files = ["docs/global-direct-target-expansion-pack.md", "examples/global-direct-target-list-builder-input.json", "examples/global-direct-target-list-builder-output.json", "examples/global-direct-target-list-builder-markdown.md", "examples/global-direct-target-list-builder.csv", "examples/global-direct-target-list-builder-high-caution.json", "examples/global-direct-target-list-builder-private-data-rejected.json", "examples/global-direct-target-list-builder-live-access-blocked.json"]; for (const file of files) { assert.equal(existsSync(join(root, file)), true, file); const content = readFileSync(join(root, file), "utf8"); assert.doesNotMatch(content, /@|https?:\/\//, file); } const input = readFileSync(inputPath, "utf8"); for (const name of ["Example North America Agent Platform", "Example UK AI Governance Team", "Example European Workflow Automation System", "Example Asia Pacific Developer Tooling Company", "Example Global Agent Protocol Project", "Example Middle East Procurement Automation System", "Example Latin America AI Security Company", "Example Africa Developer Tooling Team"]) assert.match(input, new RegExp(name)); });
