import assert from "node:assert/strict";import {spawnSync} from "node:child_process";import {existsSync,mkdtempSync,readFileSync,rmSync} from "node:fs";import type {AddressInfo} from "node:net";import {tmpdir} from "node:os";import {resolve} from "node:path";import test from "node:test";
import {createGatewayServer,createMachinePurchasePolicyReadinessReport,readLocalMachinePurchasePolicy,type GatewayRequestLogEntry,type MachinePurchasePolicyReadinessReport} from "../src/index.js";
const cli=resolve("dist/src/cli.js"),example=resolve("examples/machine-purchase-policy/machine-purchase-policy.example.json");
test("machine purchase policy readiness remains non-executing",()=>{const r=createMachinePurchasePolicyReadinessReport();assert.equal(r.machine_purchase_policy_readiness_version,"atg.machine-purchase-policy-readiness.v1");assert.equal(r.automatic_purchase_enabled,false);assert.equal(r.payment_execution_enabled,false);assert.equal(r.purchase_endpoint_enabled,false);assert.equal(r.real_charges_enabled,false);assert.equal(r.policy_model.purchase_requests_supported_in_future,true);assert.equal(r.policy_model.automatic_purchase_enabled,false);assert.equal(r.spending_control_model.default_policy,"deny_automatic_purchase");assert.equal(r.spending_control_model.automatic_purchase_limit,0);assert.equal(r.approval_model.human_approval_required,true);assert.equal(r.approval_model.agent_self_approval_allowed,false);});
test("policy evidence and future gates are explicit",()=>{const r=createMachinePurchasePolicyReadinessReport();for(const k of ["request_id_required","client_id_required","plan_code_required","entitlement_status_required"])assert.equal(r.purchase_evidence_model[k],true);assert.match(r.required_before_automatic_purchase.join(" "),/payment provider/i);assert.match(r.required_before_automatic_purchase.join(" "),/spending limits/i);assert.match(r.recommended_machine_purchase_controls.join(" "),/explicit Gareth approval/i);});
test("safe policy example parses and stays disabled",()=>{assert.equal(existsSync(example),true);const p=readLocalMachinePurchasePolicy(example).policy;assert.equal(p.automatic_purchase_enabled,false);assert.equal(p.payment_execution_enabled,false);assert.equal(p.per_purchase_limit,0);assert.doesNotMatch(readFileSync(example,"utf8"),/card_number|cvv|api[_-]?key|secret|password/i);});
test("CLI JSON, policy file, and output modes work",()=>{const j=spawnSync(process.execPath,[cli,"--machine-purchase-policy-readiness","--json"],{encoding:"utf8"});assert.equal(j.status,0);assert.equal((JSON.parse(j.stdout) as MachinePurchasePolicyReadinessReport).automatic_purchase_enabled,false);const p=spawnSync(process.execPath,[cli,"--machine-purchase-policy-readiness","--policy-file",example,"--json"],{encoding:"utf8"});assert.equal(p.status,0);const d=mkdtempSync(`${tmpdir()}\\atg-mpp-`),o=resolve(d,"x","r.json");try{assert.equal(spawnSync(process.execPath,[cli,"--machine-purchase-policy-readiness","--output",o],{encoding:"utf8"}).status,0);assert.equal(existsSync(o),true);}finally{rmSync(d,{recursive:true,force:true});}});
test("GET readiness is traced and logged",async()=>{const d=mkdtempSync(`${tmpdir()}\\atg-mpp-http-`),l=resolve(d,"g.jsonl"),s=createGatewayServer({gatewayLogPath:l});await new Promise<void>(r=>s.listen(0,"127.0.0.1",r));try{const a=s.address() as AddressInfo,res=await fetch(`http://127.0.0.1:${a.port}/v1/machine-purchase-policy-readiness`),b=await res.json() as MachinePurchasePolicyReadinessReport&{request_id:string};assert.equal(res.status,200);assert.match(b.request_id,/^gw_/);assert.equal(b.purchase_endpoint_enabled,false);}finally{await new Promise<void>((r,j)=>s.close(e=>e?j(e):r()));assert.equal((JSON.parse(readFileSync(l,"utf8")) as GatewayRequestLogEntry).endpoint,"/v1/machine-purchase-policy-readiness");rmSync(d,{recursive:true,force:true});}});
test("policy docs preserve safety boundary",()=>{const dir=resolve("docs/machine-purchase-policy"),src=["README.md","policy-model.md","spending-controls.md","approval-and-evidence.md","future-automatic-purchase-gate.md"].map(f=>readFileSync(resolve(dir,f),"utf8")).join(" ");assert.match(src,/no automatic purchase|Automatic purchase.*false/i);assert.match(src,/no payment details|No payment details/i);assert.match(src,/No billing|no billing/i);});
