import assert from"node:assert/strict";import{existsSync,readFileSync,rmSync,writeFileSync}from"node:fs";import{join}from"node:path";import test from"node:test";import{runPrivateSandboxTestHarness,summarisePrivateSandboxTestHarness,validatePrivateSandboxTestAgent,type PrivateSandboxTestHarnessInput}from"../src/private-sandbox-test-harness.js";import{runPrivateSandboxTestHarnessCli}from"../src/private-sandbox-test-harness-cli.js";const root=process.cwd(),path=join(root,"examples","private-sandbox-test-harness-input.json");const load=()=>JSON.parse(readFileSync(path,"utf8"))as PrivateSandboxTestHarnessInput;
test("ready preparation runs all fake-agent harness checks",()=>{const r=runPrivateSandboxTestHarness(load());assert.equal(r.harness_passed,true);assert.equal(r.harness_status,"harness_passed");assert.equal(r.scenario_count,4);assert.equal(r.allowed_fake_agent_passed,true);assert.equal(r.denied_non_allowlisted_agent_passed,true);assert.equal(r.missing_entitlement_passed,true);assert.equal(r.rejected_real_external_agent_passed,true);assert.equal(r.engine_ran_count,1);assert.equal(r.engine_denied_count,3);assert.ok(r.plain_english_result.length>0);assert.ok(r.recommended_next_steps.length>0)});
test("preparation not ready stops harness with reasons",()=>{const i=load();i.preparation_plan_result.plan_status="preparation_hold";const r=runPrivateSandboxTestHarness(i);assert.equal(r.harness_passed,false);assert.equal(r.harness_status,"preparation_not_ready");assert.ok(r.failure_reasons.includes("preparation_plan_not_ready"))});
test("agent validation accepts fake test only and rejects external or unmarked",()=>{assert.equal(validatePrivateSandboxTestAgent({agent_id:"a",agent_type:"fake_test_agent",sandbox_role:"r",test_only:true,fake_agent:true,external_agent:false}),true);assert.equal(validatePrivateSandboxTestAgent({agent_id:"a",agent_type:"fake_test_agent",sandbox_role:"r",test_only:true,fake_agent:true,external_agent:true}),false);assert.equal(validatePrivateSandboxTestAgent({agent_id:"a",agent_type:"agent",sandbox_role:"r"}),false)});
test("failed required scenario fails harness",()=>{const i=load();i.test_scenarios=i.test_scenarios.filter(s=>s.scenario_type!=="missing_entitlement");const r=runPrivateSandboxTestHarness(i);assert.equal(r.harness_passed,false);assert.ok(r.failure_reasons.includes("missing_entitlement_check_failed"))});
test("safety flags remain false",()=>{const r=runPrivateSandboxTestHarness(load());for(const v of[r,summarisePrivateSandboxTestHarness(r)])for(const k of["private_data_included","network_lookup_performed","external_lookup_performed","public_api_enabled","tracking_triggered","analytics_triggered","payment_or_fee_triggered","billing_triggered","settlement_triggered","machine_to_machine_fee_triggered","action_executed","deployed","published"]as const)assert.equal(v[k],false,k)});
test("private values are not copied",()=>{const i=load();Object.assign(i,{customer_name:"Private Person",api_key:"secret-key"});const o=JSON.stringify(runPrivateSandboxTestHarness(i));assert.doesNotMatch(o,/Private Person|secret-key|customer_name|api_key/)});
test("CLI supports pretty output and safe errors",()=>{const out:string[]=[];assert.equal(runPrivateSandboxTestHarnessCli([path,"--pretty"],{stdout:v=>out.push(v),stderr:()=>undefined}),0);assert.equal((JSON.parse(out[0]??"{}")as Record<string,unknown>).harness_passed,true);const bad=join(root,"harness-bad.tmp.json"),missing=join(root,"harness-missing.tmp.json"),empty=join(root,"harness-empty.tmp.json");writeFileSync(bad,"{bad");writeFileSync(missing,"{}");const x=load()as unknown as Record<string,unknown>;x.test_scenarios=[];writeFileSync(empty,JSON.stringify(x));const cases:Array<[string[],string]>=[[[],"MISSING_INPUT_FILE"],[[join(root,"absent-harness.json")],"INPUT_FILE_UNREADABLE"],[[bad],"INVALID_JSON"],[[missing],"INVALID_INPUT"],[[empty],"INVALID_INPUT"]];try{for(const[a,e]of cases){const er:string[]=[];assert.equal(runPrivateSandboxTestHarnessCli(a,{stdout:()=>undefined,stderr:v=>er.push(v)}),1);assert.equal((JSON.parse(er[0]??"{}")as{error?:{code?:string}}).error?.code,e)}}finally{for(const p of[bad,missing,empty])rmSync(p,{force:true})}});
test("docs and examples exist",()=>{for(const f of["docs/private-sandbox-test-harness.md","examples/private-sandbox-test-harness-input.json","examples/private-sandbox-test-harness-output.json","examples/private-sandbox-test-harness-preparation-not-ready.json","examples/private-sandbox-test-harness-private-data-rejected.json","examples/private-sandbox-test-harness-live-access-blocked.json"])assert.equal(existsSync(join(root,f)),true,f)});
