import assert from"node:assert/strict";import{existsSync,readFileSync,rmSync,writeFileSync}from"node:fs";import{join}from"node:path";import test from"node:test";import{createPrivateSandboxDecisionGateId,runPrivateSandboxDecisionGate,summarisePrivateSandboxDecisionGate,type PrivateSandboxDecisionGateInput}from"../src/private-sandbox-decision-gate.js";import{runPrivateSandboxDecisionGateCli}from"../src/private-sandbox-decision-gate-cli.js";
const root=process.cwd(),path=join(root,"examples","private-sandbox-decision-gate-input-ready.json");const load=()=>JSON.parse(readFileSync(path,"utf8"))as PrivateSandboxDecisionGateInput;const priv=["customer_name","customer_email","company_name","bank_account","card_number","wallet_address","api_key","access_token","private_document_text","invoice_number","contract_text","real_agent_endpoint","real_url","real_email_content"];
test("ready input passes private sandbox review gate",()=>{const r=runPrivateSandboxDecisionGate(load());assert.equal(r.private_sandbox_ready,true);assert.equal(r.readiness_status,"ready_for_private_sandbox_review");assert.equal(r.readiness_score,100);assert.equal(r.blocking_reasons.length,0);assert.match(r.go_no_go_recommendation,/GO for Gareth/);assert.match(r.plain_english_result,/passed locally/);assert.ok(r.recommended_next_steps.length>0)});
test("failed checks lower deterministic score and return reasons",()=>{const i=load();i.sandbox_smoke_test_result.smoke_test_passed=false;i.sandbox_smoke_test_result.missing_entitlement_blocked=false;i.profit_demo_result.entitled_use_passed=false;const a=runPrivateSandboxDecisionGate(i),b=runPrivateSandboxDecisionGate(i);assert.equal(a.private_sandbox_ready,false);assert.equal(a.readiness_score,b.readiness_score);assert.ok(a.readiness_score<100);assert.ok(a.blocking_reasons.length>0)});
test("safety violation blocks and missing Gareth gate prevents readiness",()=>{const i=load();i.safety_flags.public_api_enabled=true;i.required_approvals.requires_gareth_final_approval=false;const r=runPrivateSandboxDecisionGate(i);assert.equal(r.private_sandbox_ready,false);assert.ok(r.blocking_reasons.includes("safety_flag_violation"));assert.ok(r.blocking_reasons.includes("gareth_final_approval_gate_missing"));assert.equal(r.gareth_final_approval_required,true)});
test("safety output and summary remain false",()=>{const r=runPrivateSandboxDecisionGate(load());for(const v of[r,summarisePrivateSandboxDecisionGate(r)])for(const k of["private_data_included","network_lookup_performed","external_lookup_performed","public_api_enabled","tracking_triggered","analytics_triggered","payment_or_fee_triggered","billing_triggered","settlement_triggered","machine_to_machine_fee_triggered","action_executed","deployed","published"]as const)assert.equal(v[k],false,k)});
test("ID and private stripping",()=>{const id=createPrivateSandboxDecisionGateId("private@example.test");assert.equal(id,createPrivateSandboxDecisionGateId("private@example.test"));assert.doesNotMatch(id,/@|example\.test/i);const i=load();Object.assign(i,{customer_name:"Private Person",api_key:"secret-key"});const o=JSON.stringify(runPrivateSandboxDecisionGate(i));for(const f of priv)assert.equal(o.includes(f),false);assert.doesNotMatch(o,/Private Person|secret-key/)});
test("CLI works and handles local errors",()=>{const out:string[]=[];assert.equal(runPrivateSandboxDecisionGateCli([path,"--pretty"],{stdout:v=>out.push(v),stderr:()=>undefined}),0);assert.equal((JSON.parse(out[0]??"{}")as Record<string,unknown>).private_sandbox_ready,true);const bad=join(root,"decision-bad.tmp.json"),missing=join(root,"decision-missing.tmp.json");writeFileSync(bad,"{bad");writeFileSync(missing,"{}");const cases:Array<[string[],string]>=[[[],"MISSING_INPUT_FILE"],[[join(root,"absent-decision.json")],"INPUT_FILE_UNREADABLE"],[[bad],"INVALID_JSON"],[[missing],"INVALID_INPUT"]];try{for(const[a,e]of cases){const err:string[]=[];assert.equal(runPrivateSandboxDecisionGateCli(a,{stdout:()=>undefined,stderr:v=>err.push(v)}),1);assert.equal((JSON.parse(err[0]??"{}")as{error?:{code?:string}}).error?.code,e)}}finally{rmSync(bad,{force:true});rmSync(missing,{force:true})}});
test("docs and examples exist",()=>{for(const f of["docs/private-sandbox-decision-gate.md","examples/private-sandbox-decision-gate-input-ready.json","examples/private-sandbox-decision-gate-output-ready.json","examples/private-sandbox-decision-gate-output-blocked.json","examples/private-sandbox-decision-gate-private-data-rejected.json","examples/private-sandbox-decision-gate-live-access-blocked.json"])assert.equal(existsSync(join(root,f)),true,f)});
