import assert from"node:assert/strict";import{existsSync,readFileSync,rmSync,writeFileSync}from"node:fs";import{join}from"node:path";import test from"node:test";import{createSandboxSmokeTestId,runSandboxEndToEndSmokeTest,summariseSandboxEndToEndSmokeTest,type SandboxEndToEndSmokeTestInput}from"../src/sandbox-end-to-end-smoke-test.js";import{runSandboxEndToEndSmokeTestCli}from"../src/sandbox-end-to-end-smoke-test-cli.js";
const root=process.cwd(),path=join(root,"examples","sandbox-end-to-end-smoke-test-input.json");const load=()=>JSON.parse(readFileSync(path,"utf8"))as SandboxEndToEndSmokeTestInput;const privateFields=["customer_name","customer_email","company_name","bank_account","card_number","wallet_address","api_key","access_token","private_document_text","invoice_number","contract_text","real_agent_endpoint","real_url","real_email_content"];
test("smoke test passes all three sandbox checks",()=>{const r=runSandboxEndToEndSmokeTest(load());assert.equal(r.scenario_count,3);assert.equal(r.allowed_sandbox_agent_passed,true);assert.equal(r.denied_sandbox_agent_blocked,true);assert.equal(r.missing_entitlement_blocked,true);assert.equal(r.engine_ran_count,1);assert.equal(r.engine_denied_count,2);assert.equal(r.smoke_test_passed,true);assert.equal(r.failure_reasons.length,0);assert.match(r.plain_english_result,/smoke test passed/i);assert.ok(r.recommended_next_steps.length>0)});
test("smoke failure returns reasons",()=>{const i=load();i.scenarios=i.scenarios.slice(0,2);const r=runSandboxEndToEndSmokeTest(i);assert.equal(r.smoke_test_passed,false);assert.ok(r.failure_reasons.length>0)});
test("safety flags remain false in result and summary",()=>{const r=runSandboxEndToEndSmokeTest(load());for(const v of[r,summariseSandboxEndToEndSmokeTest(r)])for(const k of["private_data_included","network_lookup_performed","external_lookup_performed","public_api_enabled","tracking_triggered","analytics_triggered","payment_or_fee_triggered","billing_triggered","settlement_triggered","machine_to_machine_fee_triggered","action_executed","deployed","published"]as const)assert.equal(v[k],false,k)});
test("deterministic ID and private stripping",()=>{const id=createSandboxSmokeTestId("private@example.test");assert.equal(id,createSandboxSmokeTestId("private@example.test"));assert.doesNotMatch(id,/private|example/i);const i=load();Object.assign(i,{customer_name:"Private",api_key:"secret"});const o=JSON.stringify(runSandboxEndToEndSmokeTest(i));for(const f of privateFields)assert.equal(o.includes(f),false);assert.doesNotMatch(o,/Private|secret/)});
test("CLI works with pretty JSON",()=>{const out:string[]=[];assert.equal(runSandboxEndToEndSmokeTestCli([path,"--pretty"],{stdout:v=>out.push(v),stderr:()=>undefined}),0);assert.match(out[0]??"",/\n  "smoke_test_id"/);assert.equal((JSON.parse(out[0]??"{}")as Record<string,unknown>).smoke_test_passed,true)});
test("CLI handles missing file JSON and scenarios",()=>{const bad=join(root,"smoke-bad.tmp.json"),missing=join(root,"smoke-missing.tmp.json"),empty=join(root,"smoke-empty.tmp.json");writeFileSync(bad,"{bad");writeFileSync(missing,"{}");writeFileSync(empty,'{"scenarios":[]}');const cases:Array<[string[],string]>=[[[],"MISSING_INPUT_FILE"],[[join(root,"absent-smoke.json")],"INPUT_FILE_UNREADABLE"],[[bad],"INVALID_JSON"],[[missing],"INVALID_INPUT"],[[empty],"INVALID_INPUT"]];try{for(const[a,e]of cases){const err:string[]=[];assert.equal(runSandboxEndToEndSmokeTestCli(a,{stdout:()=>undefined,stderr:v=>err.push(v)}),1);assert.equal((JSON.parse(err[0]??"{}")as{error?:{code?:string}}).error?.code,e)}}finally{for(const p of[bad,missing,empty])rmSync(p,{force:true})}});
test("docs and examples exist",()=>{for(const f of["docs/sandbox-end-to-end-smoke-test.md","examples/sandbox-end-to-end-smoke-test-input.json","examples/sandbox-end-to-end-smoke-test-output.json","examples/sandbox-end-to-end-smoke-test-private-data-rejected.json","examples/sandbox-end-to-end-smoke-test-live-access-blocked.json"])assert.equal(existsSync(join(root,f)),true,f)});
