import { createHash } from "node:crypto";

export const AGENT_TO_AGENT_DISCOVERY_PACK_VERSION = "atg.agent-to-agent-discovery-pack.v1" as const;
export type AgentDiscoveryStatus = "discovery_pack_ready" | "discovery_pack_hold" | "discovery_pack_blocked" | "unknown";
export interface AgentToAgentDiscoveryPackInput { [key: string]: unknown; discovery_pack_id?: string; source_id: string; educational_review_pack_result?: Record<string, unknown>; manual_outreach_approval_queue_result?: Record<string, unknown>; pilot_offer_result?: Record<string, unknown>; quantum_readiness_policy?: Record<string, unknown>; safety_flags?: Record<string, unknown>; created_at: string }
export interface AgentCardArtifact { schema_version: string; agent_name: string; product_name: string; description: string; provider: string; discovery_status: string; capabilities_summary: string; skills: string[]; supported_interactions: string[]; disabled_interactions: string[]; access_model: string[]; approval_required: true; live_endpoint_available: false; public_api_available: false; production_ready: false; sandbox_available: true; contact_policy: string[]; safety_boundaries: string[]; quantum_readiness: string; next_step: string }
export interface AgentReadableOfferArtifact { offer_type: string; product_name: string; buyer_problem: string; pilot_scope: string[]; review_scope: string[]; accepted_agent_types: string[]; prohibited_agent_types: string[]; pilot_deliverables: string[]; disabled_capabilities: string[]; required_approvals: string[]; commercial_follow_up_policy: string; pricing_status: string; next_step: string }
export interface TechnicalReviewArtifact { review_type: string; technical_learning_objective: string; review_topics: string[]; fake_agent_sandbox_scope: string[]; evidence_and_receipt_topics: string[]; refusal_signal_topics: string[]; replay_topics: string[]; human_approval_topics: string[]; excessive_agency_boundary: string; quantum_readiness_topics: string[]; disabled_capabilities: string[]; required_approvals: string[]; next_step: string }
export interface AgentToAgentDiscoveryPack { discovery_pack_id: string; discovery_pack_type: "local_agent_to_agent_discovery"; source_id: string; product_name: "Agent Trust Gate™"; owner_name: "Gareth"; discovery_status: AgentDiscoveryStatus; machine_readable_positioning: { one_liner: string; discovery_purpose: string; status: string[] }; agent_card: AgentCardArtifact; agent_readable_offer: AgentReadableOfferArtifact; technical_review: TechnicalReviewArtifact; capabilities: Record<string, true>; disabled_capabilities: Record<string, true>; private_pilot_manifest: Record<string, unknown>; human_approval_policy: Record<string, unknown>; pricing_pilot_metadata: Record<string, unknown>; llms_txt: string; developer_discovery_markdown: string; safety_boundaries: string[]; quantum_readiness_positioning: Record<string, unknown>; agent_to_agent_ready_for_review: boolean; machine_to_machine_discovery_supported: true; live_agent_access_enabled: false; public_endpoint_available: false; hosted_discovery_available: false; gareth_approval_required_before_publishing: true; gareth_approval_required_before_live_agent_access: true; what_agents_can_understand: string[]; what_agents_cannot_do_yet: string[]; recommended_next_steps: string[]; plain_english_summary: string; private_data_included: false; network_lookup_performed: false; external_lookup_performed: false; public_api_enabled: false; tracking_triggered: false; analytics_triggered: false; payment_or_fee_triggered: false; billing_triggered: false; settlement_triggered: false; machine_to_machine_fee_triggered: false; action_executed: false; email_sent: false; message_sent: false; scraped: false; deployed: false; published: false; status: "discovery_pack_only"; created_at: string }
export type AgentToAgentDiscoveryPackSummary = Pick<AgentToAgentDiscoveryPack, "discovery_pack_id" | "discovery_status" | "agent_to_agent_ready_for_review" | "machine_to_machine_discovery_supported" | "live_agent_access_enabled" | "public_endpoint_available" | "hosted_discovery_available" | "gareth_approval_required_before_publishing" | "gareth_approval_required_before_live_agent_access" | "plain_english_summary" | "private_data_included" | "network_lookup_performed" | "external_lookup_performed" | "public_api_enabled" | "tracking_triggered" | "analytics_triggered" | "payment_or_fee_triggered" | "billing_triggered" | "settlement_triggered" | "machine_to_machine_fee_triggered" | "action_executed" | "email_sent" | "message_sent" | "scraped" | "deployed" | "published" | "status">;

const ONE_LINER = "Pre-action clearing for AI agents before they access data, spend money, call tools, or trigger external actions.";
const PURPOSE = "Allow agent systems, developer tools, and AI platforms to understand the concept, capabilities, limitations, review path, disabled capabilities, and private pilot route without live access.";
const DISABLED_NAMES = ["Public API", "Live endpoint", "Real external agents", "Real customer data", "Real payment", "Billing", "Settlement", "Live machine-to-machine fees", "Autonomous action execution", "Tool execution", "Email and message sending", "Scraping and internet search", "Tracking and analytics", "Deployment and publishing", "Production integration", "Quantum-security and post-quantum-compliance claims", "Production post-quantum cryptographic controls"];
const SAFETY = ["Local files and deterministic rendering only", "No public API, endpoint, hosting, network, or live agent access", "No real customer data, credentials, contact details, or private data", "No payment, billing, settlement, tracking, analytics, or execution", "No publication without Gareth approval", "No legal, compliance, audit, quantum-security, or PQC-compliance certification claim"];
const CAPABILITY_KEYS = ["local_fake_agent_sandbox_demo", "pre_action_intent_check", "entitlement_check", "allow_deny_approval_gate", "refusal_signal_awareness", "receipt_generation", "receipt_verification", "evidence_bundle", "replay_runner", "readiness_scoring", "manual_approval_queue", "machine_readable_discovery_files", "quantum_readiness_positioning_only"] as const;
const DISABLED_KEYS = ["public_api", "live_endpoint", "real_external_agents", "real_customer_data", "real_payment", "billing", "settlement", "machine_to_machine_live_fee", "autonomous_action_execution", "tool_execution", "email_sending", "message_sending", "scraping", "internet_search", "tracking", "analytics", "deployment", "publishing", "production_integration", "quantum_security_claim", "post_quantum_compliance_claim", "ML_KEM_implementation", "ML_DSA_implementation", "SLH_DSA_implementation"] as const;
const BLOCKED_FLAGS = ["public_api_enabled", "live_endpoint_enabled", "live_agent_access_enabled", "hosted_discovery_enabled", "deployment_enabled", "publishing_enabled", "payment_enabled", "billing_enabled", "settlement_enabled", "machine_to_machine_fee_enabled", "tracking_enabled", "analytics_enabled", "action_execution_enabled", "scraping_enabled", "internet_search_enabled", "external_lookup_enabled", "email_sending_enabled", "message_sending_enabled", "private_data_included", "quantum_security_claimed", "post_quantum_compliance_claimed", "nist_certification_claimed"] as const;

export function createAgentToAgentDiscoveryPack(input: AgentToAgentDiscoveryPackInput): AgentToAgentDiscoveryPack {
  const safety = input.safety_flags ?? {}, quantumPolicy = input.quantum_readiness_policy ?? {};
  const blocked = BLOCKED_FLAGS.some(key => safety[key] === true || quantumPolicy[key] === true);
  const complete = input.educational_review_pack_result?.review_status === "educational_review_pack_ready" && input.manual_outreach_approval_queue_result?.queue_status === "queue_ready_for_gareth_review" && input.pilot_offer_result?.commercial_status === "draft_private_pilot_offer_ready";
  const discoveryStatus: AgentDiscoveryStatus = blocked ? "discovery_pack_blocked" : complete ? "discovery_pack_ready" : "discovery_pack_hold";
  const capabilities = trueMap(CAPABILITY_KEYS), disabled = trueMap(DISABLED_KEYS);
  const quantum = { quantum_claim_level: "positioning_only", quantum_security_claimed: false, post_quantum_compliance_claimed: false, nist_certified: false, production_cryptography_implemented: false, future_pqc_migration_awareness: true, cryptographic_inventory_placeholders: ["Future integration dependencies", "Future signing and verification mechanisms", "Future receipt integrity mechanisms"], implementations_not_present: ["ML-KEM", "ML-DSA", "SLH-DSA"] };
  const offer: AgentReadableOfferArtifact = { offer_type: "private_fake_agent_sandbox_pilot", product_name: "Agent Trust Gate™", buyer_problem: "Agent systems need a clear permission gate before tools, data, spend, or external actions.", pilot_scope: ["Local fake-agent sandbox", "Pre-action clearing and entitlement", "Receipts, evidence, replay, and denied scenarios"], review_scope: ["Education-first technical review", "Developer, platform, governance, and security feedback"], accepted_agent_types: ["Fake agents", "Test agents", "Local system simulations"], prohibited_agent_types: ["Real external agents", "Production agents", "Agents carrying real customer data"], pilot_deliverables: ["Allow, deny, and approval-gate outcomes", "Receipt and verification output", "Evidence bundle and replay", "Manual approval queue"], disabled_capabilities: [...DISABLED_NAMES], required_approvals: ["Gareth approval before publishing", "Gareth approval before live access", "Separate target and message approvals"], commercial_follow_up_policy: "Only after interest, mutual fit, and separate Gareth approval.", pricing_status: "draft_local_metadata_only", next_step: discoveryStatus === "discovery_pack_ready" ? "Gareth reviews these local discovery artifacts." : "Hold until every local readiness input is complete." };
  const review: TechnicalReviewArtifact = { review_type: "educational_agent_system_technical_review", technical_learning_objective: "Review how permission, entitlement, refusal, evidence, receipts, replay, and human approval can constrain agents before action.", review_topics: ["Pre-action clearing", "Entitlement and approval gates", "Excessive-agency boundaries"], fake_agent_sandbox_scope: ["Local fake/test agents only", "Synthetic data only", "No external integration"], evidence_and_receipt_topics: ["Receipt creation and local verification", "Evidence bundle boundaries"], refusal_signal_topics: ["RefusalGraph-style local refusal intelligence", "Denied scenario reasoning"], replay_topics: ["Deterministic replay consistency", "Mismatch identification"], human_approval_topics: ["Target and message approval", "Approval before external or high-impact action"], excessive_agency_boundary: "Requested actions are cleared and described but never executed.", quantum_readiness_topics: ["Positioning only", "Future cryptographic inventory", "Future PQC migration awareness"], disabled_capabilities: [...DISABLED_NAMES], required_approvals: ["Gareth review", "Technical and security review before future live work"], next_step: "Review local JSON and sandbox artifacts only." };
  const pilotManifest = { manifest_type: "private_fake_agent_pilot", product_name: "Agent Trust Gate™", pilot_status: "draft_review_only", pilot_mode: ["fake_agent_only", "local_review_only", "no_live_access"], accepted_inputs: ["Synthetic local JSON", "Fake/test-agent scenarios"], prohibited_inputs: ["Private data", "Credentials", "Real customer data", "Live agent requests"], sandbox_boundaries: ["No network", "No server", "No action execution"], review_boundaries: ["Educational and technical review only", "No certification"], approval_gates: ["Gareth approval before publishing", "Gareth approval before live access"], disabled_capabilities: [...DISABLED_NAMES], next_step: "Run local review commands only." };
  const approvalPolicy = { policy_type: "gareth_manual_approval", owner: "Gareth", approvals_required_for: ["Publishing discovery files", "Live agent access", "External sharing", "Payment discussion", "Action execution"], approvals_not_granted_for: ["Go-live", "Public API", "Live endpoint", "Autonomous execution"], manual_review_required: true, live_access_requires_future_approval: true, publishing_requires_future_approval: true, payment_requires_future_approval: true, action_execution_requires_future_approval: true };
  const pricing = { pricing_status: "draft_local_metadata_only", pricing_options: [{ name: "Educational technical review", range: "£0 introductory review" }, { name: "Private fake-agent sandbox pilot", range: "£500-£1,500" }, { name: "Extended pilot", range: "£2,500-£5,000" }], currency: "GBP", payment_links_available: false, billing_enabled: false, invoice_generated: false, commercial_terms_require_manual_approval: true, pilot_follow_up_only_after_interest: true };
  const card: AgentCardArtifact = { schema_version: "atg.agent-card.v1", agent_name: "Agent Trust Gate local discovery", product_name: "Agent Trust Gate™", description: ONE_LINER, provider: "Gareth", discovery_status: "local_discovery_only", capabilities_summary: "Local fake-agent pre-action clearing, receipts, evidence, replay, readiness, and manual approval artifacts.", skills: Object.keys(capabilities), supported_interactions: ["Read local discovery JSON", "Review local fake-agent examples", "Request human-reviewed technical feedback"], disabled_interactions: [...DISABLED_NAMES], access_model: ["local_discovery_only", "review_only", "no_live_endpoint"], approval_required: true, live_endpoint_available: false, public_api_available: false, production_ready: false, sandbox_available: true, contact_policy: ["Manual Gareth review only", "No automatic outreach or live agent connection"], safety_boundaries: [...SAFETY], quantum_readiness: "Positioning only; not quantum secure or post-quantum compliant.", next_step: "Gareth reviews the local pack before any publishing or live-access decision." };
  const llms = createLlmsTxt(capabilities, disabled), ready = discoveryStatus === "discovery_pack_ready";
  const pack = { discovery_pack_id: createAgentToAgentDiscoveryPackId(input.discovery_pack_id ?? input.source_id), discovery_pack_type: "local_agent_to_agent_discovery", source_id: safeId(input.source_id), product_name: "Agent Trust Gate™", owner_name: "Gareth", discovery_status: discoveryStatus, machine_readable_positioning: { one_liner: ONE_LINER, discovery_purpose: PURPOSE, status: ["local_discovery_only", "review_only", "no_live_endpoint"] }, agent_card: card, agent_readable_offer: offer, technical_review: review, capabilities, disabled_capabilities: disabled, private_pilot_manifest: pilotManifest, human_approval_policy: approvalPolicy, pricing_pilot_metadata: pricing, llms_txt: llms, developer_discovery_markdown: "", safety_boundaries: [...SAFETY], quantum_readiness_positioning: quantum, agent_to_agent_ready_for_review: ready, machine_to_machine_discovery_supported: true, live_agent_access_enabled: false, public_endpoint_available: false, hosted_discovery_available: false, gareth_approval_required_before_publishing: true, gareth_approval_required_before_live_agent_access: true, what_agents_can_understand: ["Product purpose and pre-action clearing concept", "Local capabilities and disabled capabilities", "Fake-agent review and private-pilot boundaries", "Human approval and cautious quantum-readiness positioning"], what_agents_cannot_do_yet: ["Call a live endpoint or public API", "Connect as a real external agent", "Trigger tools, actions, payments, billing, or settlement", "Publish, deploy, track, scrape, search, or send messages"], recommended_next_steps: ready ? ["Gareth reviews each local artifact", "Keep all artifacts unpublished", "Obtain separate approval before any future hosted or live-access design"] : ["Complete missing local readiness inputs", "Keep discovery local and unpublished"], plain_english_summary: ready ? "The local machine-readable discovery pack is ready for Gareth review. Nothing was published, hosted, networked, connected, charged, tracked, or executed." : discoveryStatus === "discovery_pack_blocked" ? "The discovery pack is blocked by a prohibited live, commercial, private-data, or certification condition. Nothing was published." : "The discovery pack is on hold until all local readiness inputs are complete. Nothing was published.", private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "discovery_pack_only", created_at: safeTime(input.created_at) } as AgentToAgentDiscoveryPack;
  pack.developer_discovery_markdown = renderAgentToAgentDiscoveryMarkdown(pack);
  return pack;
}

export function createAgentToAgentDiscoveryPackId(sourceId: string): string { return "agent_to_agent_discovery_pack_" + createHash("sha256").update(sourceId, "utf8").digest("hex").slice(0, 24); }
export function summariseAgentToAgentDiscoveryPack(pack: AgentToAgentDiscoveryPack): AgentToAgentDiscoveryPackSummary { const { discovery_pack_id, discovery_status, agent_to_agent_ready_for_review, machine_to_machine_discovery_supported, live_agent_access_enabled, public_endpoint_available, hosted_discovery_available, gareth_approval_required_before_publishing, gareth_approval_required_before_live_agent_access, plain_english_summary, private_data_included, network_lookup_performed, external_lookup_performed, public_api_enabled, tracking_triggered, analytics_triggered, payment_or_fee_triggered, billing_triggered, settlement_triggered, machine_to_machine_fee_triggered, action_executed, email_sent, message_sent, scraped, deployed, published, status } = pack; return { discovery_pack_id, discovery_status, agent_to_agent_ready_for_review, machine_to_machine_discovery_supported, live_agent_access_enabled, public_endpoint_available, hosted_discovery_available, gareth_approval_required_before_publishing, gareth_approval_required_before_live_agent_access, plain_english_summary, private_data_included, network_lookup_performed, external_lookup_performed, public_api_enabled, tracking_triggered, analytics_triggered, payment_or_fee_triggered, billing_triggered, settlement_triggered, machine_to_machine_fee_triggered, action_executed, email_sent, message_sent, scraped, deployed, published, status }; }
export function renderAgentCardJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.agent_card); }
export function renderAgentReadableOfferJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.agent_readable_offer); }
export function renderTechnicalReviewJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.technical_review); }
export function renderCapabilitiesJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.capabilities); }
export function renderDisabledCapabilitiesJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.disabled_capabilities); }
export function renderPrivatePilotManifestJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.private_pilot_manifest); }
export function renderHumanApprovalPolicyJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.human_approval_policy); }
export function renderPricingPilotMetadataJson(pack: AgentToAgentDiscoveryPack): string { return pretty(pack.pricing_pilot_metadata); }
export function renderLlmsTxt(pack: AgentToAgentDiscoveryPack): string { return pack.llms_txt; }
export function renderAgentToAgentDiscoveryMarkdown(pack: AgentToAgentDiscoveryPack): string { const section = (heading: string, values: readonly string[]) => [`## ${heading}`, ...values.map(value => `- ${value}`), ""]; return ["# Agent-to-Agent Discovery Pack", "", "Local discovery pack only. Nothing has been published. No endpoint, public API, hosted discovery, or live agent access exists.", "", "## Machine-Readable Positioning", pack.machine_readable_positioning.one_liner, "", "## Agent Card Summary", pack.agent_card.capabilities_summary, "", ...section("Capabilities", Object.keys(pack.capabilities)), ...section("Disabled Capabilities", Object.keys(pack.disabled_capabilities)), "## Private Pilot Manifest", "- fake_agent_only", "- local_review_only", "- no_live_access", "", "## Human Approval Policy", "Gareth approval is required before publishing, live access, payment discussion, or action execution.", "", "## Pricing / Pilot Metadata", "Draft local metadata only. Payment links, billing, and invoices are disabled.", "", "## llms.txt Preview", pack.llms_txt, "", "## Quantum-Readiness Positioning", "Positioning only. No quantum-security or PQC-compliance claim is made. No ML-KEM, ML-DSA, or SLH-DSA implementation exists.", "", ...section("What Agents Can Understand", pack.what_agents_can_understand), ...section("What Agents Cannot Do Yet", pack.what_agents_cannot_do_yet), ...section("Safety Boundaries", pack.safety_boundaries), "## Gareth Approval Gate", "Gareth approval is required before any publication or future live agent access.", "", ...section("Recommended Next Steps", pack.recommended_next_steps), "No scraping, searching, contact, sending, payment, billing, settlement, tracking, analytics, deployment, publishing, or action execution occurred."].join("\n"); }
function createLlmsTxt(capabilities: Record<string, true>, disabled: Record<string, true>): string { return ["# Agent Trust Gate™", "", ONE_LINER, "", "## What it does", "Describes a local pre-action clearing pattern with fake-agent review, receipts, evidence, replay, and human approval.", "", "## Currently available", ...Object.keys(capabilities).map(key => `- ${key}`), "", "## Disabled", ...Object.keys(disabled).map(key => `- ${key}`), "", "## Interpretation", "This pack is local discovery metadata only. It is not a callable service.", "", "## Human approval", "Gareth approval is required before publishing or live agent access.", "", "## Quantum readiness", "Positioning only: future inventory and PQC migration awareness. Not quantum secure, post-quantum compliant, NIST certified, or a production cryptographic implementation.", "", "No production API or live endpoint exists. No legal, compliance, audit, security, or quantum certification is claimed."].join("\n"); }
function trueMap(keys: readonly string[]): Record<string, true> { return Object.fromEntries(keys.map(key => [key, true])) as Record<string, true>; }
function pretty(value: unknown): string { return JSON.stringify(value, null, 2); }
function safeId(value: string): string { return "source_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 20); }
function safeTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "1970-01-01T00:00:00.000Z" : date.toISOString(); }
