import { readFileSync } from "node:fs";
import { createAgentToAgentDiscoveryPack, renderAgentCardJson, renderAgentReadableOfferJson, renderAgentToAgentDiscoveryMarkdown, renderCapabilitiesJson, renderDisabledCapabilitiesJson, renderHumanApprovalPolicyJson, renderLlmsTxt, renderPricingPilotMetadataJson, renderPrivatePilotManifestJson, renderTechnicalReviewJson, type AgentToAgentDiscoveryPackInput } from "./agent-to-agent-discovery-pack.js";
export type AgentDiscoveryCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "DISCOVERY_ERROR";
export interface AgentDiscoveryCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: AgentDiscoveryCliErrorCode, message: string) { super(message); } }
const defaultIo: AgentDiscoveryCliIo = { stdout: console.log, stderr: console.error };
type Mode = "json" | "agent-card" | "offer-json" | "technical-review-json" | "capabilities-json" | "disabled-capabilities-json" | "pilot-manifest-json" | "human-approval-policy-json" | "pricing-json" | "llms-txt" | "markdown";
export function runAgentToAgentDiscoveryPackCli(args: readonly string[], io: AgentDiscoveryCliIo = defaultIo): number { try { const options = parse(args), pack = createAgentToAgentDiscoveryPack(readAgentToAgentDiscoveryPackInput(options.path)); const renderers: Record<Exclude<Mode, "json">, () => string> = { "agent-card": () => renderAgentCardJson(pack), "offer-json": () => renderAgentReadableOfferJson(pack), "technical-review-json": () => renderTechnicalReviewJson(pack), "capabilities-json": () => renderCapabilitiesJson(pack), "disabled-capabilities-json": () => renderDisabledCapabilitiesJson(pack), "pilot-manifest-json": () => renderPrivatePilotManifestJson(pack), "human-approval-policy-json": () => renderHumanApprovalPolicyJson(pack), "pricing-json": () => renderPricingPilotMetadataJson(pack), "llms-txt": () => renderLlmsTxt(pack), "markdown": () => renderAgentToAgentDiscoveryMarkdown(pack) }; io.stdout(options.mode === "json" ? JSON.stringify(pack, null, options.pretty ? 2 : 0) : renderers[options.mode]()); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readAgentToAgentDiscoveryPackInput(path: string): AgentToAgentDiscoveryPackInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local discovery input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local discovery input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const record = value as Record<string, unknown>; if (typeof record.educational_review_pack_result !== "object" || record.educational_review_pack_result === null || Array.isArray(record.educational_review_pack_result)) throw invalid("Missing educational_review_pack_result."); if (typeof record.source_id !== "string" || typeof record.created_at !== "string") throw invalid("Missing required local metadata."); return record as unknown as AgentToAgentDiscoveryPackInput; }
function parse(args: readonly string[]) { let path: string | undefined; let pretty = false; let mode: Mode = "json"; let selected = false; const modes: Record<string, Mode> = { "--agent-card": "agent-card", "--offer-json": "offer-json", "--technical-review-json": "technical-review-json", "--capabilities-json": "capabilities-json", "--disabled-capabilities-json": "disabled-capabilities-json", "--pilot-manifest-json": "pilot-manifest-json", "--human-approval-policy-json": "human-approval-policy-json", "--pricing-json": "pricing-json", "--llms-txt": "llms-txt", "--markdown": "markdown" }; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = modes[arg]; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported discovery option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "DISCOVERY_ERROR", message: known ? error.message : "The local discovery pack could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, live_agent_access_enabled: false, public_endpoint_available: false, hosted_discovery_available: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "discovery_pack_only" }; }
if (process.argv[1]?.endsWith("agent-to-agent-discovery-pack-cli.js")) process.exitCode = runAgentToAgentDiscoveryPackCli(process.argv.slice(2));
