import { createHash } from "node:crypto";

export const DIRECT_TARGET_LIST_BUILDER_VERSION = "atg.direct-target-list-builder.v1" as const;
export type DirectTargetCategory = "ai_agent_platform" | "workflow_automation_system" | "enterprise_ai_governance" | "ai_security_company" | "procurement_automation" | "finance_operations_automation" | "developer_tooling" | "agent_protocol_or_marketplace" | "other";
export type GarethTargetApprovalStatus = "not_reviewed" | "approved_for_manual_contact_draft" | "hold" | "reject";
export type TargetPriorityBand = "high_priority" | "medium_priority" | "low_priority" | "not_recommended";
export type TargetListCommercialStatus = "target_list_ready_for_gareth_review" | "target_list_hold" | "target_list_blocked" | "unknown";
export interface DirectTargetInput { [key: string]: unknown; target_id?: string; target_name?: string; target_category?: string; target_description?: string; likely_buyer_role?: string; agent_system_relevance?: string; governance_need?: string; payment_or_action_risk?: string; evidence_need?: string; integration_complexity?: string; commercial_fit?: string; pilot_budget_likelihood?: string; public_contact_known?: boolean; contact_channel?: string; gareth_approval_status?: string; notes?: string }
export interface DirectTargetListInput { [key: string]: unknown; target_list_id?: string; source_id: string; owner_name?: string; offer_pack_result: Record<string, unknown>; targets: DirectTargetInput[]; scoring_policy?: unknown; contact_policy?: unknown; safety_flags?: Record<string, unknown>; created_at: string }
export interface ScoredDirectTarget { target_id: string; target_name: string; target_category: DirectTargetCategory; likely_buyer_role: string; reason_they_might_care: string; pilot_fit_score: number; priority_band: TargetPriorityBand; risk_level: "high" | "medium" | "low" | "unknown"; recommended_message_angle: string; contact_readiness: "ready_for_gareth_message_review" | "manual_review_required" | "held" | "rejected"; gareth_approval_status: GarethTargetApprovalStatus; next_manual_action: string; rejection_reason: string | null }
export interface DirectTargetListResult { target_list_id: string; target_list_type: "manual_private_pilot_target_list"; source_id: string; owner_name: "Gareth"; commercial_status: TargetListCommercialStatus; input_target_count: number; accepted_target_count: number; rejected_target_count: number; targets: ScoredDirectTarget[]; top_priority_targets: ScoredDirectTarget[]; target_summary: { high_priority: number; medium_priority: number; low_priority: number; not_recommended: number; approved_for_manual_contact_draft: number }; scoring_policy: string[]; contact_policy: string[]; manual_review_required: true; gareth_approval_required_before_contact: true; no_automatic_contact: true; no_scraping_performed: true; no_external_lookup_performed: true; recommended_next_steps: string[]; plain_english_summary: string; private_data_included: false; network_lookup_performed: false; external_lookup_performed: false; public_api_enabled: false; tracking_triggered: false; analytics_triggered: false; payment_or_fee_triggered: false; billing_triggered: false; settlement_triggered: false; machine_to_machine_fee_triggered: false; action_executed: false; email_sent: false; message_sent: false; scraped: false; deployed: false; published: false; status: "target_list_only"; created_at: string }
export type DirectTargetListSummary = Omit<DirectTargetListResult, "targets" | "top_priority_targets" | "scoring_policy" | "contact_policy" | "recommended_next_steps" | "created_at">;

const CATEGORIES = new Set<DirectTargetCategory>(["ai_agent_platform", "workflow_automation_system", "enterprise_ai_governance", "ai_security_company", "procurement_automation", "finance_operations_automation", "developer_tooling", "agent_protocol_or_marketplace", "other"]);
const APPROVALS = new Set<GarethTargetApprovalStatus>(["not_reviewed", "approved_for_manual_contact_draft", "hold", "reject"]);
const BLOCKING_FLAGS = ["scraping_enabled", "network_lookup_enabled", "network_enabled", "automatic_contact_enabled", "email_sending_enabled", "message_sending_enabled", "payment_enabled", "billing_enabled", "settlement_enabled", "action_execution_enabled", "public_api_enabled", "deployment_enabled", "publishing_enabled", "private_data_included"] as const;
const SCORING = ["High agent-system relevance: +20", "High governance need: +20", "High payment/action risk: +15", "High evidence need: +15", "High commercial fit: +15", "High pilot-budget likelihood: +10", "Low integration complexity: +5", "High integration complexity: -10", "Scores are clamped from 0 to 100"];
const CONTACT_POLICY = ["No automatic contact", "No scraping or external target discovery", "No mass outreach or unsolicited automated messaging", "Gareth manually reviews every target", "Gareth manually approves every message", "Any contact occurs outside this tool unless separately approved in a future mission"];

export function buildDirectTargetList(input: DirectTargetListInput): DirectTargetListResult {
  const safety = input.safety_flags ?? {};
  const blocked = BLOCKING_FLAGS.some(key => safety[key] === true);
  const scored = rankDirectTargets(input.targets.map(scoreDirectTarget));
  const accepted = scored.filter(target => target.rejection_reason === null);
  const rejected = scored.filter(target => target.rejection_reason !== null);
  const approvedCount = accepted.filter(target => target.gareth_approval_status === "approved_for_manual_contact_draft").length;
  const offerReady = input.offer_pack_result.commercial_status === "draft_private_pilot_offer_ready";
  const allLow = accepted.length > 0 && accepted.every(target => target.pilot_fit_score < 60);
  let commercialStatus: TargetListCommercialStatus;
  if (blocked) commercialStatus = "target_list_blocked";
  else if (offerReady && accepted.length > 0 && approvedCount > 0 && !allLow) commercialStatus = "target_list_ready_for_gareth_review";
  else commercialStatus = "target_list_hold";
  const targetSummary = { high_priority: accepted.filter(t => t.priority_band === "high_priority").length, medium_priority: accepted.filter(t => t.priority_band === "medium_priority").length, low_priority: accepted.filter(t => t.priority_band === "low_priority").length, not_recommended: accepted.filter(t => t.priority_band === "not_recommended").length, approved_for_manual_contact_draft: approvedCount };
  return { target_list_id: createDirectTargetListBuilderId(input.target_list_id ?? input.source_id), target_list_type: "manual_private_pilot_target_list", source_id: safeId(input.source_id), owner_name: "Gareth", commercial_status: commercialStatus, input_target_count: input.targets.length, accepted_target_count: accepted.length, rejected_target_count: rejected.length, targets: scored, top_priority_targets: accepted.filter(target => target.priority_band === "high_priority").slice(0, 5), target_summary: targetSummary, scoring_policy: [...SCORING], contact_policy: [...CONTACT_POLICY], manual_review_required: true, gareth_approval_required_before_contact: true, no_automatic_contact: true, no_scraping_performed: true, no_external_lookup_performed: true, recommended_next_steps: nextSteps(commercialStatus, accepted), plain_english_summary: summary(commercialStatus, accepted.length, rejected.length), private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "target_list_only", created_at: safeTime(input.created_at) };
}

export function scoreDirectTarget(target: DirectTargetInput): ScoredDirectTarget {
  const name = safeTargetName(target.target_name);
  const category = safeCategory(target.target_category);
  const approval = safeApproval(target.gareth_approval_status);
  const rejection = !name ? "missing_or_unsafe_target_name" : approval === "reject" ? "rejected_by_gareth" : null;
  let score = 0;
  score += points(target.agent_system_relevance, 20);
  score += points(target.governance_need, 20);
  score += points(target.payment_or_action_risk, 15);
  score += points(target.evidence_need, 15);
  score += points(target.commercial_fit, 15);
  score += points(target.pilot_budget_likelihood, 10);
  if (target.integration_complexity === "low") score += 5;
  if (target.integration_complexity === "high") score -= 10;
  score = rejection ? 0 : Math.max(0, Math.min(100, score));
  const priority = band(score);
  return { target_id: safeTargetId(target.target_id ?? name ?? "rejected"), target_name: name ?? "Rejected target", target_category: category, likely_buyer_role: buyerRole(category), reason_they_might_care: reason(category), pilot_fit_score: score, priority_band: priority, risk_level: safeLevel(target.payment_or_action_risk), recommended_message_angle: messageAngle(category), contact_readiness: rejection ? "rejected" : approval === "approved_for_manual_contact_draft" ? "ready_for_gareth_message_review" : approval === "hold" ? "held" : "manual_review_required", gareth_approval_status: approval, next_manual_action: rejection ? "Do not contact; keep the record rejected." : approval === "approved_for_manual_contact_draft" ? "Gareth reviews a locally drafted, target-specific message; this tool sends nothing." : approval === "hold" ? "Resolve the hold before drafting contact." : "Gareth manually reviews fit before any message is drafted.", rejection_reason: rejection };
}

export function rankDirectTargets(targets: readonly ScoredDirectTarget[]): ScoredDirectTarget[] { return [...targets].sort((a, b) => b.pilot_fit_score - a.pilot_fit_score || a.target_id.localeCompare(b.target_id)); }
export function createDirectTargetListBuilderId(sourceId: string): string { return "direct_target_list_builder_" + createHash("sha256").update(sourceId, "utf8").digest("hex").slice(0, 24); }
export function summariseDirectTargetList(result: DirectTargetListResult): DirectTargetListSummary { const { targets: _a, top_priority_targets: _b, scoring_policy: _c, contact_policy: _d, recommended_next_steps: _e, created_at: _f, ...summaryResult } = result; return summaryResult; }
export function renderDirectTargetListMarkdown(result: DirectTargetListResult): string { const list = (heading: string, values: readonly string[]) => [`## ${heading}`, ...(values.length ? values : ["None"]).map(value => `- ${value}`), ""]; return ["# Direct Target List Builder", "", "Local target planning only. No scraping, searching, contact, email, or message has occurred.", "", `## Commercial Status\n${result.commercial_status}`, "", `## Target Summary\nAccepted: ${result.accepted_target_count}; rejected: ${result.rejected_target_count}; high priority: ${result.target_summary.high_priority}.`, "", ...list("Top Priority Targets", result.top_priority_targets.map(target => `${target.target_name} (${target.pilot_fit_score})`)), ...list("Target Details", result.targets.map(target => `${target.target_name}: ${target.priority_band}; ${target.contact_readiness}; ${target.next_manual_action}`)), ...list("Scoring Policy", result.scoring_policy), ...list("Contact Policy", result.contact_policy), "## Gareth Approval Gate", "Gareth must manually review every target and approve every message before any contact.", "", "## What Remains Disabled", "No public API, live agents, payment, billing, settlement, tracking, analytics, deployment, publishing, scraping, or action execution is enabled.", "", ...list("Recommended Next Steps", result.recommended_next_steps)].join("\n"); }
export function renderDirectTargetListCsv(result: DirectTargetListResult): string { const headers = ["target_id", "target_name", "target_category", "likely_buyer_role", "pilot_fit_score", "priority_band", "risk_level", "contact_readiness", "gareth_approval_status", "recommended_message_angle", "next_manual_action"] as const; const rows = result.targets.map(target => headers.map(header => csv(String(target[header]))).join(",")); return [headers.join(","), ...rows].join("\n"); }

function points(value: unknown, maximum: number): number { return value === "high" ? maximum : value === "medium" ? Math.floor(maximum / 2) : 0; }
function band(score: number): TargetPriorityBand { return score >= 80 ? "high_priority" : score >= 60 ? "medium_priority" : score >= 40 ? "low_priority" : "not_recommended"; }
function safeLevel(value: unknown): "high" | "medium" | "low" | "unknown" { return value === "high" || value === "medium" || value === "low" ? value : "unknown"; }
function safeCategory(value: unknown): DirectTargetCategory { return typeof value === "string" && CATEGORIES.has(value as DirectTargetCategory) ? value as DirectTargetCategory : "other"; }
function safeApproval(value: unknown): GarethTargetApprovalStatus { return typeof value === "string" && APPROVALS.has(value as GarethTargetApprovalStatus) ? value as GarethTargetApprovalStatus : "not_reviewed"; }
function safeTargetName(value: unknown): string | null { if (typeof value !== "string") return null; const clean = value.trim().replace(/\s+/g, " ").slice(0, 80); return clean.length > 0 && !/[@<>]|https?:|www\./i.test(clean) ? clean : null; }
function safeTargetId(value: string): string { return "target_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 16); }
function safeId(value: string): string { return "source_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 20); }
function safeTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "1970-01-01T00:00:00.000Z" : date.toISOString(); }
function buyerRole(category: DirectTargetCategory): string { const roles: Record<DirectTargetCategory, string> = { ai_agent_platform: "Agent platform product or engineering lead", workflow_automation_system: "Automation product or operations lead", enterprise_ai_governance: "AI governance or risk lead", ai_security_company: "AI security product lead", procurement_automation: "Procurement automation product lead", finance_operations_automation: "Finance automation or controls lead", developer_tooling: "Developer platform or tooling lead", agent_protocol_or_marketplace: "Agent ecosystem or protocol lead", other: "System owner or technical decision maker" }; return roles[category]; }
function reason(category: DirectTargetCategory): string { return category === "enterprise_ai_governance" || category === "ai_security_company" ? "They may need evidence-backed pre-action controls for agent decisions." : category === "procurement_automation" || category === "finance_operations_automation" ? "They may need entitlement and approval gates before agent-driven spend or external actions." : "They may need a consistent allow, deny, and approval gate before agent tools or workflows run."; }
function messageAngle(category: DirectTargetCategory): string { return category === "ai_security_company" ? "Lead with refusal intelligence, evidence, and deterministic denied scenarios." : category === "enterprise_ai_governance" ? "Lead with pre-action governance evidence, receipts, and replay." : category === "procurement_automation" || category === "finance_operations_automation" ? "Lead with entitlement, approval, and spend/action gating without money movement." : "Lead with a local fake-agent demonstration of pre-action clearance and receipts."; }
function nextSteps(status: TargetListCommercialStatus, accepted: readonly ScoredDirectTarget[]): string[] { if (status === "target_list_blocked") return ["Do not proceed", "Remove the prohibited capability and rebuild locally"]; if (status === "target_list_ready_for_gareth_review") return ["Gareth reviews the ranked placeholder targets", "Select at most one target for a separate local message draft", "Do not contact or share without explicit message approval"]; return accepted.length ? ["Gareth reviews target fit and approval status", "Keep all contact disabled"] : ["Add manually supplied placeholder targets", "Do not search or scrape for targets"]; }
function summary(status: TargetListCommercialStatus, accepted: number, rejected: number): string { return status === "target_list_ready_for_gareth_review" ? `Local target list ready for Gareth review with ${accepted} accepted placeholder targets and ${rejected} rejected records. No scraping, search, contact, email, or message occurred.` : status === "target_list_blocked" ? "Target-list building is blocked because a prohibited capability was requested. No contact or external activity occurred." : "Target list is on hold pending suitable manually supplied targets, offer readiness, or Gareth review. No contact or external activity occurred."; }
function csv(value: string): string { return `"${value.replace(/"/g, '""').replace(/[\r\n]/g, " ")}"`; }
