import { readFileSync } from "node:fs";
import { buildDirectTargetList, renderDirectTargetListCsv, renderDirectTargetListMarkdown, type DirectTargetListInput } from "./direct-target-list-builder.js";
export type DirectTargetListCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "EMPTY_TARGETS" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "TARGET_LIST_ERROR";
export interface DirectTargetListCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: DirectTargetListCliErrorCode, message: string) { super(message); } }
const defaultIo: DirectTargetListCliIo = { stdout: console.log, stderr: console.error };
export function runDirectTargetListBuilderCli(args: readonly string[], io: DirectTargetListCliIo = defaultIo): number { try { const options = parse(args); const result = buildDirectTargetList(readDirectTargetListInput(options.path)); io.stdout(options.mode === "markdown" ? renderDirectTargetListMarkdown(result) : options.mode === "csv" ? renderDirectTargetListCsv(result) : JSON.stringify(result, null, options.pretty ? 2 : 0)); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readDirectTargetListInput(path: string): DirectTargetListInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local target-list input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local target-list input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const record = value as Record<string, unknown>; if (typeof record.offer_pack_result !== "object" || record.offer_pack_result === null || Array.isArray(record.offer_pack_result)) throw invalid("Missing offer_pack_result."); if (!Array.isArray(record.targets)) throw invalid("Missing targets."); if (record.targets.length === 0) throw new CliError("EMPTY_TARGETS", "At least one manually supplied target is required by the CLI."); if (typeof record.source_id !== "string" || typeof record.created_at !== "string") throw invalid("Missing required local metadata."); return record as unknown as DirectTargetListInput; }
function parse(args: readonly string[]) { let path: string | undefined; let pretty = false; let mode: "json" | "markdown" | "csv" = "json"; let selected = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = arg === "--markdown" ? "markdown" : arg === "--csv" ? "csv" : undefined; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported target-list option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "TARGET_LIST_ERROR", message: known ? error.message : "The local target list could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, no_automatic_contact: true, no_scraping_performed: true, no_external_lookup_performed: true, status: "target_list_only" }; }
if (process.argv[1]?.endsWith("direct-target-list-builder-cli.js")) process.exitCode = runDirectTargetListBuilderCli(process.argv.slice(2));
