import { createHash } from "node:crypto";

export const DIRECT_AGENT_SYSTEM_PILOT_OFFER_PACK_VERSION = "atg.direct-agent-system-pilot-offer-pack.v1" as const;
export type PilotOfferCommercialStatus = "draft_private_pilot_offer_ready" | "hold_for_gareth_approval";
export interface DirectAgentSystemPilotOfferPackInput { [key: string]: unknown; offer_pack_id?: string; source_id: string; product_name?: string; owner_name?: string; approval_record_result: Record<string, unknown>; target_audience?: unknown; pilot_scope?: unknown; pricing_options?: unknown; contact_channel_policy?: unknown; created_at: string }
export interface PilotPricingOption { name: string; price: string; scope: string; manual_approval_required: true }
export interface MachineReadablePilotOffer { offer_type: "private_fake_agent_sandbox_pilot"; product_name: "Agent Trust Gate™"; pilot_scope: string[]; accepted_agent_types: string[]; prohibited_agent_types: string[]; sandbox_capabilities: string[]; disabled_capabilities: string[]; required_approvals: string[]; commercial_interest_signal: string; next_step: string }
export interface DirectAgentSystemPilotOfferPack {
  offer_pack_id: string; offer_pack_type: "direct_agent_system_private_pilot_offer"; source_id: string; product_name: "Agent Trust Gate™"; owner_name: "Gareth"; commercial_status: PilotOfferCommercialStatus;
  offer_positioning: string; buyer_problem: string; target_audience: string[]; target_system_profile: string[]; ideal_private_pilot_customer: string[]; disqualified_customer_profile: string[]; direct_pilot_offer: string; pilot_scope: string[]; pilot_deliverables: string[]; pilot_pricing_options: PilotPricingOption[]; pilot_access_rules: string[]; qualification_questions: string[];
  machine_readable_offer: MachineReadablePilotOffer; human_readable_brief: string; direct_contact_message: string; technical_invitation_message: string; what_the_pilot_proves: string[]; what_the_pilot_does_not_prove: string[]; what_remains_disabled: string[]; gareth_approval_required_before_sending: true; next_allowed_local_step: string; forbidden_steps: string[]; plain_english_summary: string; recommended_next_steps: string[];
  private_data_included: false; network_lookup_performed: false; external_lookup_performed: false; public_api_enabled: false; tracking_triggered: false; analytics_triggered: false; payment_or_fee_triggered: false; billing_triggered: false; settlement_triggered: false; machine_to_machine_fee_triggered: false; action_executed: false; email_sent: false; message_sent: false; scraped: false; deployed: false; published: false; status: "offer_pack_only"; created_at: string;
}
export type DirectAgentSystemPilotOfferPackSummary = Pick<DirectAgentSystemPilotOfferPack, "offer_pack_id" | "commercial_status" | "product_name" | "direct_pilot_offer" | "gareth_approval_required_before_sending" | "plain_english_summary" | "private_data_included" | "network_lookup_performed" | "external_lookup_performed" | "public_api_enabled" | "tracking_triggered" | "analytics_triggered" | "payment_or_fee_triggered" | "billing_triggered" | "settlement_triggered" | "machine_to_machine_fee_triggered" | "action_executed" | "email_sent" | "message_sent" | "scraped" | "deployed" | "published" | "status">;

const AUDIENCE = ["AI agent platform builders", "AI workflow automation companies", "Enterprise AI governance teams", "AI security companies", "Procurement automation systems", "Financial operations automation teams", "Developer tooling companies building agent infrastructure", "Agent-to-agent protocol or marketplace builders"];
const SCOPE = ["Controlled local fake-agent sandbox demonstration", "Pre-action intent and entitlement checks", "Allow, deny, and human-approval-required outcomes", "Local receipts, evidence bundles, replay, and readiness summaries"];
const CAPABILITIES = ["Agent intent checks", "Entitlement checks", "Allow/deny decisions", "RefusalGraph-style refusal intelligence", "Local receipts", "Evidence bundle", "Replay", "Readiness scoring", "Denied unsafe scenarios"];
const DISABLED = ["Public API and network access", "Real or external agents and real customer data", "Payment, billing, settlement, invoices, and payment links", "Live machine-to-machine fees", "Tracking, analytics, scraping, and automated outreach", "Deployment, publishing, webhooks, and action execution"];
const APPROVALS = ["Gareth approval for each target", "Gareth approval for each message", "Technical scope review", "Security and data-boundary review", "Commercial scope review"];

export function createDirectAgentSystemPilotOfferPack(input: DirectAgentSystemPilotOfferPackInput): DirectAgentSystemPilotOfferPack {
  const approved = input.approval_record_result.approval_status === "approved_for_local_demo_pack_preparation";
  const commercial_status: PilotOfferCommercialStatus = approved ? "draft_private_pilot_offer_ready" : "hold_for_gareth_approval";
  const directContact = "Hi [Name], I’m preparing a private pilot for Agent Trust Gate™, a pre-action clearing layer for AI agents before they access data, spend money, call tools, or trigger external actions. It currently runs as a local fake-agent sandbox demo with allow/deny decisions, entitlement checks, receipts, evidence bundles, and replay. Would your team be interested in reviewing a controlled private pilot?";
  const technical = "We are preparing a controlled Agent Trust Gate™ private pilot for agent/platform teams. The local fake-agent sandbox applies pre-action clearance, entitlement checks, allow/deny gates, RefusalGraph-style refusal intelligence, receipts, evidence bundles, replay, and explicit safety flags. There is no production API yet, no real money movement, and no live action execution.";
  const machine: MachineReadablePilotOffer = { offer_type: "private_fake_agent_sandbox_pilot", product_name: "Agent Trust Gate™", pilot_scope: [...SCOPE], accepted_agent_types: ["Allowlisted fake agents", "Allowlisted test agents", "Locally defined system simulations"], prohibited_agent_types: ["Real external agents", "Production agents", "Agents carrying real customer data"], sandbox_capabilities: [...CAPABILITIES], disabled_capabilities: [...DISABLED], required_approvals: [...APPROVALS], commercial_interest_signal: "Manual expression of interest in a controlled private pilot", next_step: approved ? "Gareth manually reviews a named target and the draft message before any contact." : "Hold until Gareth records the required local approval." };
  return {
    offer_pack_id: createDirectAgentSystemPilotOfferPackId(input.offer_pack_id ?? input.source_id), offer_pack_type: "direct_agent_system_private_pilot_offer", source_id: safeId(input.source_id), product_name: "Agent Trust Gate™", owner_name: "Gareth", commercial_status,
    offer_positioning: "Pre-action clearing for AI agents before they access data, spend money, call tools, or trigger external actions.", buyer_problem: "Agent systems need a safe, auditable permission gate before agents act.", target_audience: [...AUDIENCE], target_system_profile: ["Builds or governs agent workflows", "Has pre-action permission or trust concerns", "Can evaluate a local fake/test-agent sandbox", "Accepts manual review and a tightly bounded pilot"], ideal_private_pilot_customer: ["Has a concrete agent action-gating use case", "Can use fake/test agents and synthetic data", "Will nominate technical and business reviewers"], disqualified_customer_profile: ["Requires immediate production or public API access", "Requires real customer data or real external agents", "Requires guaranteed safety or certification", "Requires payment processing or autonomous execution"],
    direct_pilot_offer: "A controlled fake-agent sandbox demonstration of pre-action clearing, entitlement gating, evidence, and denied unsafe scenarios.", pilot_scope: [...SCOPE], pilot_deliverables: [...CAPABILITIES], pilot_pricing_options: [{ name: "Free technical discovery call", price: "£0", scope: "Manual fit and use-case review", manual_approval_required: true }, { name: "Private sandbox pilot", price: "£500-£1,500", scope: "Scope-limited fake/test-agent pilot", manual_approval_required: true }, { name: "Extended pilot", price: "£2,500-£5,000", scope: "Deeper workflow mapping and evidence review", manual_approval_required: true }], pilot_access_rules: ["Fake/test agents and synthetic data only", "Local files and controlled demonstrations only", "No access without manual scope approval"], qualification_questions: ["What agent action needs a pre-action gate?", "Which data, tool, spend, or external-action boundary matters?", "Can the evaluation use fake/test agents and synthetic data only?", "Who owns technical, security, and commercial review?", "What result would make a private pilot useful?"],
    machine_readable_offer: machine, human_readable_brief: "Agent Trust Gate™ offers a controlled private pilot showing how agent requests can be entitlement-gated, cleared, refused, receipted, replayed, and reviewed before any action. The current offer is draft, local, and fake-agent only.", direct_contact_message: directContact, technical_invitation_message: technical,
    what_the_pilot_proves: ["The local clearing flow can produce deterministic allow, deny, or approval-required outcomes", "Entitlement and unsafe-case denials can be demonstrated", "Local receipts, evidence, replay, and readiness outputs can be reviewed"], what_the_pilot_does_not_prove: ["Legal or regulatory compliance", "Guaranteed safety, fraud prevention, or certified audit", "Production scale, live agent networking, payment processing, or production API readiness"], what_remains_disabled: [...DISABLED], gareth_approval_required_before_sending: true, next_allowed_local_step: approved ? "Gareth may review a named target and tailored draft locally." : "Resolve local owner approval before preparing any target-specific draft.", forbidden_steps: ["Automatic sending or mass outreach", "Scraping or lead harvesting", "Publishing this pack", "Adding links, credentials, endpoints, or payment collection", "Connecting real agents or executing actions"],
    plain_english_summary: approved ? "A draft private pilot offer is ready for local review. It can be tailored to a manually selected agent/system builder only after Gareth approves the target and message. Nothing has been sent, published, billed, deployed, scraped, networked, or executed." : "The pilot offer is on hold because the required local owner approval record is not approved. Nothing may be sent or shared.", recommended_next_steps: approved ? ["Gareth reviews the offer and pricing", "Gareth manually selects one qualified target", "Prepare one local target-specific draft for separate approval", "Do not send or share until Gareth explicitly approves"] : ["Obtain the narrow local demo-pack approval", "Keep all contact and commercial activity disabled"],
    private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "offer_pack_only", created_at: safeTime(input.created_at)
  };
}

export function createDirectAgentSystemPilotOfferPackId(sourceId: string): string { return "direct_agent_system_pilot_offer_pack_" + createHash("sha256").update(sourceId, "utf8").digest("hex").slice(0, 24); }
export function summariseDirectAgentSystemPilotOfferPack(pack: DirectAgentSystemPilotOfferPack): DirectAgentSystemPilotOfferPackSummary { const { offer_pack_id, commercial_status, product_name, direct_pilot_offer, gareth_approval_required_before_sending, plain_english_summary, private_data_included, network_lookup_performed, external_lookup_performed, public_api_enabled, tracking_triggered, analytics_triggered, payment_or_fee_triggered, billing_triggered, settlement_triggered, machine_to_machine_fee_triggered, action_executed, email_sent, message_sent, scraped, deployed, published, status } = pack; return { offer_pack_id, commercial_status, product_name, direct_pilot_offer, gareth_approval_required_before_sending, plain_english_summary, private_data_included, network_lookup_performed, external_lookup_performed, public_api_enabled, tracking_triggered, analytics_triggered, payment_or_fee_triggered, billing_triggered, settlement_triggered, machine_to_machine_fee_triggered, action_executed, email_sent, message_sent, scraped, deployed, published, status }; }
export function renderDirectAgentSystemPilotOfferJson(pack: DirectAgentSystemPilotOfferPack): string { return JSON.stringify(pack.machine_readable_offer, null, 2); }
export function renderDirectPilotContactMessage(pack: DirectAgentSystemPilotOfferPack): string { return pack.direct_contact_message; }
export function renderDirectAgentSystemPilotOfferPackMarkdown(pack: DirectAgentSystemPilotOfferPack): string { const section = (heading: string, values: readonly string[]) => [`## ${heading}`, ...values.map(value => `- ${value}`), ""]; return ["# Direct Agent/System Pilot Offer Pack", "", "Draft/local offer material only. Nothing has been sent.", "", "## Product Positioning", pack.offer_positioning, "", "## Buyer Problem", pack.buyer_problem, "", ...section("Ideal Pilot Customers", pack.ideal_private_pilot_customer), ...section("Disqualified Customers", pack.disqualified_customer_profile), "## Private Pilot Offer", pack.direct_pilot_offer, "", ...section("What Pilot Users Receive", pack.pilot_deliverables), "## Pricing Options", ...pack.pilot_pricing_options.map(option => `- ${option.name}: ${option.price} - ${option.scope}`), "", "## Direct Contact Message", pack.direct_contact_message, "", "## Technical Invitation Message", pack.technical_invitation_message, "", "## Machine-Readable Offer Summary", `- Offer type: ${pack.machine_readable_offer.offer_type}`, `- Next step: ${pack.machine_readable_offer.next_step}`, "", ...section("What Remains Disabled", pack.what_remains_disabled), "## Gareth Approval Gate", "Gareth must manually approve each target and message before anything is sent or shared.", "", ...section("Forbidden Steps", pack.forbidden_steps), ...section("Recommended Next Steps", pack.recommended_next_steps), "No public API, live agents, payment, billing, settlement, tracking, analytics, deployment, publishing, scraping, or action execution is enabled."].join("\n"); }
function safeId(value: string): string { return "source_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 20); }
function safeTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "1970-01-01T00:00:00.000Z" : date.toISOString(); }
