import { readFileSync } from "node:fs";
import { createDirectAgentSystemPilotOfferPack, renderDirectAgentSystemPilotOfferJson, renderDirectAgentSystemPilotOfferPackMarkdown, renderDirectPilotContactMessage, type DirectAgentSystemPilotOfferPackInput } from "./direct-agent-system-pilot-offer-pack.js";
export type DirectPilotOfferCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "OFFER_PACK_ERROR";
export interface DirectPilotOfferCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: DirectPilotOfferCliErrorCode, message: string) { super(message); } }
const defaultIo: DirectPilotOfferCliIo = { stdout: console.log, stderr: console.error };
export function runDirectAgentSystemPilotOfferPackCli(args: readonly string[], io: DirectPilotOfferCliIo = defaultIo): number { try { const options = parse(args); const pack = createDirectAgentSystemPilotOfferPack(readDirectAgentSystemPilotOfferPackInput(options.path)); const output = options.mode === "markdown" ? renderDirectAgentSystemPilotOfferPackMarkdown(pack) : options.mode === "offer-json" ? renderDirectAgentSystemPilotOfferJson(pack) : options.mode === "contact-message" ? renderDirectPilotContactMessage(pack) : JSON.stringify(pack, null, options.pretty ? 2 : 0); io.stdout(output); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readDirectAgentSystemPilotOfferPackInput(path: string): DirectAgentSystemPilotOfferPackInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local offer-pack input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local offer-pack input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const record = value as Record<string, unknown>; if (typeof record.approval_record_result !== "object" || record.approval_record_result === null || Array.isArray(record.approval_record_result)) throw invalid("Missing approval_record_result."); if (typeof record.source_id !== "string" || typeof record.created_at !== "string") throw invalid("Missing required local metadata."); return record as unknown as DirectAgentSystemPilotOfferPackInput; }
function parse(args: readonly string[]) { let path: string | undefined; let pretty = false; let mode: "json" | "markdown" | "offer-json" | "contact-message" = "json"; let selected = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = arg === "--markdown" ? "markdown" : arg === "--offer-json" ? "offer-json" : arg === "--contact-message" ? "contact-message" : undefined; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported offer-pack option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "OFFER_PACK_ERROR", message: known ? error.message : "The local pilot offer pack could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "offer_pack_only" }; }
if (process.argv[1]?.endsWith("direct-agent-system-pilot-offer-pack-cli.js")) process.exitCode = runDirectAgentSystemPilotOfferPackCli(process.argv.slice(2));
