import { createHash } from "node:crypto";

export const GARETH_MANUAL_OUTREACH_APPROVAL_QUEUE_VERSION = "atg.gareth-manual-outreach-approval-queue.v1" as const;
export type OutreachDecision = "not_reviewed" | "approved" | "hold" | "rejected" | "rewrite_required";
export type ManualContactStatus = "not_contacted" | "manually_contacted_outside_tool" | "replied_interested" | "replied_not_interested" | "no_response" | "do_not_contact" | "unknown";
export type InterestStatus = "unknown" | "no_interest" | "possible_interest" | "interested_in_technical_review" | "interested_in_private_pilot" | "not_relevant";
export type ManualReviewPriority = "urgent_review" | "high_review" | "medium_review" | "low_review" | "not_recommended";
export type OutreachQueueStatus = "queue_ready_for_gareth_review" | "queue_hold" | "queue_blocked" | "unknown";
export interface OutreachQueueItemInput { [key: string]: unknown; queue_item_id?: string; target_id?: string; target_name?: string; region?: string; country_or_market?: string; target_category?: string; likely_buyer_role?: string; global_pilot_fit_score?: number; global_priority_band?: string; jurisdiction_contact_caution?: string; recommended_message_angle?: string; first_contact_message?: string; technical_invitation_message?: string; pilot_follow_up_message?: string; gareth_target_decision?: string; gareth_first_contact_decision?: string; gareth_technical_invite_decision?: string; gareth_pilot_follow_up_decision?: string; manual_contact_status?: string; interest_status?: string; notes?: string }
export interface GarethManualOutreachApprovalQueueInput { [key: string]: unknown; queue_id?: string; source_id: string; owner_name?: string; global_target_list_result?: Record<string, unknown>; educational_review_pack_result?: Record<string, unknown>; queue_items: OutreachQueueItemInput[]; approval_policy?: Record<string, unknown>; contact_policy?: Record<string, unknown>; safety_flags?: Record<string, unknown>; created_at: string }
export interface ScoredOutreachQueueItem { queue_item_id: string; target_id: string; target_name: string; region: string; country_or_market: string; target_category: string; likely_buyer_role: string; global_pilot_fit_score: number; global_priority_band: string; jurisdiction_contact_caution: "low" | "medium" | "high" | "unknown"; outreach_queue_score: number; manual_review_priority: ManualReviewPriority; gareth_target_decision: OutreachDecision; gareth_first_contact_decision: OutreachDecision; gareth_technical_invite_decision: OutreachDecision; gareth_pilot_follow_up_decision: OutreachDecision; manual_contact_status: ManualContactStatus; interest_status: InterestStatus; allowed_next_manual_step: string; forbidden_next_steps: string[]; recommended_message_type: "educational_first_contact" | "technical_invitation" | "commercial_pilot_follow_up" | "none"; recommended_manual_action: string; safety_notes: string[]; rejection_reason: string | null }
export interface GarethManualOutreachApprovalQueue { queue_id: string; queue_type: "gareth_manual_outreach_approval_queue"; source_id: string; owner_name: "Gareth"; queue_status: OutreachQueueStatus; input_item_count: number; approved_target_count: number; held_target_count: number; rejected_target_count: number; approved_first_contact_count: number; approved_technical_invite_count: number; approved_pilot_follow_up_count: number; not_reviewed_count: number; queue_items: ScoredOutreachQueueItem[]; top_manual_review_items: ScoredOutreachQueueItem[]; approval_summary: Record<string, number>; contact_policy: string[]; approval_policy: string[]; manual_contact_status_summary: Record<string, number>; jurisdiction_contact_caution_summary: Record<string, number>; gareth_approval_required_before_contact: true; gareth_approval_required_before_each_message: true; pilot_follow_up_allowed_only_after_interest: true; no_automatic_contact: true; no_scraping_performed: true; no_external_lookup_performed: true; no_email_sent: true; no_message_sent: true; recommended_next_steps: string[]; plain_english_summary: string; private_data_included: false; network_lookup_performed: false; external_lookup_performed: false; public_api_enabled: false; tracking_triggered: false; analytics_triggered: false; payment_or_fee_triggered: false; billing_triggered: false; settlement_triggered: false; machine_to_machine_fee_triggered: false; action_executed: false; email_sent: false; message_sent: false; scraped: false; deployed: false; published: false; status: "approval_queue_only"; created_at: string }
export type GarethManualOutreachApprovalQueueSummary = Omit<GarethManualOutreachApprovalQueue, "queue_items" | "top_manual_review_items" | "contact_policy" | "approval_policy" | "recommended_next_steps" | "created_at">;

const DECISIONS = new Set<OutreachDecision>(["not_reviewed", "approved", "hold", "rejected", "rewrite_required"]);
const CONTACT_STATUSES = new Set<ManualContactStatus>(["not_contacted", "manually_contacted_outside_tool", "replied_interested", "replied_not_interested", "no_response", "do_not_contact", "unknown"]);
const INTEREST_STATUSES = new Set<InterestStatus>(["unknown", "no_interest", "possible_interest", "interested_in_technical_review", "interested_in_private_pilot", "not_relevant"]);
const INTERESTED = new Set<InterestStatus>(["possible_interest", "interested_in_technical_review", "interested_in_private_pilot"]);
const BLOCKING_FLAGS = ["automatic_outreach_enabled", "scraping_enabled", "external_lookup_enabled", "network_lookup_enabled", "email_sending_enabled", "message_sending_enabled", "public_api_enabled", "payment_enabled", "billing_enabled", "settlement_enabled", "tracking_enabled", "analytics_enabled", "deployment_enabled", "publishing_enabled", "action_execution_enabled", "private_data_included"] as const;
const CONTACT_POLICY = ["All contact remains manual", "Gareth must approve every target before contact", "Gareth must approve every message before contact", "No automated global outreach", "No mass emailing", "No scraping or lead harvesting", "No unsolicited automated messaging", "No internet lookup performed", "No personal data copied", "Actual contact happens outside this tool unless separately approved in a future mission", "Pilot follow-up is allowed only after interest is shown"];
const APPROVAL_POLICY = ["Target approval is required before any message approval", "Educational first-contact may be approved before manual contact", "Technical invitation requires target approval", "Commercial pilot follow-up requires target approval and recorded interest", "Rejected and do-not-contact targets block all future steps", "This tool records decisions but sends nothing"];

export function createGarethManualOutreachApprovalQueue(input: GarethManualOutreachApprovalQueueInput): GarethManualOutreachApprovalQueue {
  const contact = input.contact_policy ?? {}, safety = input.safety_flags ?? {};
  const improperFollowUp = input.queue_items.some(item => safeDecision(item.gareth_pilot_follow_up_decision) === "approved" && !INTERESTED.has(safeInterest(item.interest_status)));
  const blocked = improperFollowUp || BLOCKING_FLAGS.some(key => contact[key] === true || safety[key] === true);
  const items = rankOutreachQueueItems(input.queue_items.map(scoreOutreachQueueItem));
  const educationalReady = input.educational_review_pack_result?.review_status === "educational_review_pack_ready";
  const targetReady = Boolean(input.global_target_list_result) && (input.global_target_list_result?.commercial_status === "target_list_ready_for_gareth_review" || items.length > 0);
  const allNotReviewed = items.length > 0 && items.every(item => item.gareth_target_decision === "not_reviewed");
  const allRewrite = items.length > 0 && items.every(item => item.gareth_first_contact_decision === "rewrite_required" && item.gareth_technical_invite_decision === "rewrite_required");
  let queueStatus: OutreachQueueStatus;
  if (blocked) queueStatus = "queue_blocked";
  else if (targetReady && educationalReady && items.length > 0 && !allNotReviewed && !allRewrite) queueStatus = "queue_ready_for_gareth_review";
  else queueStatus = "queue_hold";
  const targetCounts = count(items.map(item => item.gareth_target_decision));
  const contactCounts = count(items.map(item => item.manual_contact_status));
  const cautionCounts = count(items.map(item => item.jurisdiction_contact_caution));
  const approvedFirst = items.filter(item => item.gareth_first_contact_decision === "approved").length, approvedTechnical = items.filter(item => item.gareth_technical_invite_decision === "approved").length, approvedPilot = items.filter(item => item.gareth_pilot_follow_up_decision === "approved").length;
  return { queue_id: createGarethManualOutreachApprovalQueueId(input.queue_id ?? input.source_id), queue_type: "gareth_manual_outreach_approval_queue", source_id: safeId(input.source_id), owner_name: "Gareth", queue_status: queueStatus, input_item_count: input.queue_items.length, approved_target_count: targetCounts.approved ?? 0, held_target_count: (targetCounts.hold ?? 0) + (targetCounts.rewrite_required ?? 0), rejected_target_count: targetCounts.rejected ?? 0, approved_first_contact_count: approvedFirst, approved_technical_invite_count: approvedTechnical, approved_pilot_follow_up_count: approvedPilot, not_reviewed_count: targetCounts.not_reviewed ?? 0, queue_items: items, top_manual_review_items: items.filter(item => item.manual_review_priority === "urgent_review" || item.manual_review_priority === "high_review").slice(0, 5), approval_summary: { approved_targets: targetCounts.approved ?? 0, held_targets: targetCounts.hold ?? 0, rejected_targets: targetCounts.rejected ?? 0, approved_first_contacts: approvedFirst, approved_technical_invites: approvedTechnical, approved_pilot_follow_ups: approvedPilot }, contact_policy: [...CONTACT_POLICY], approval_policy: [...APPROVAL_POLICY], manual_contact_status_summary: contactCounts, jurisdiction_contact_caution_summary: cautionCounts, gareth_approval_required_before_contact: true, gareth_approval_required_before_each_message: true, pilot_follow_up_allowed_only_after_interest: true, no_automatic_contact: true, no_scraping_performed: true, no_external_lookup_performed: true, no_email_sent: true, no_message_sent: true, recommended_next_steps: nextSteps(queueStatus, items), plain_english_summary: queueStatus === "queue_ready_for_gareth_review" ? "The local manual outreach queue is ready for Gareth review. Decisions are recorded only; no search, scraping, contact, email, or message occurred." : queueStatus === "queue_blocked" ? "The local queue is blocked by a prohibited capability or a pilot follow-up approval without recorded interest. Nothing was sent." : "The local queue is on hold pending ready inputs or reviewed targets. Nothing was sent.", private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "approval_queue_only", created_at: safeTime(input.created_at) };
}

export function scoreOutreachQueueItem(item: OutreachQueueItemInput): ScoredOutreachQueueItem {
  const name = safeName(item.target_name), targetDecision = safeDecision(item.gareth_target_decision), contactStatus = safeContact(item.manual_contact_status), interest = safeInterest(item.interest_status), targetApproved = targetDecision === "approved", stopped = !name || targetDecision === "rejected" || contactStatus === "do_not_contact";
  const first = effectiveMessageDecision(item.gareth_first_contact_decision, targetApproved, stopped), technical = effectiveMessageDecision(item.gareth_technical_invite_decision, targetApproved, stopped), requestedPilot = safeDecision(item.gareth_pilot_follow_up_decision), pilot = effectiveMessageDecision(requestedPilot, targetApproved && INTERESTED.has(interest), stopped);
  const fit = safeScore(item.global_pilot_fit_score); let score = Math.round(fit * 0.6); score += item.global_priority_band === "global_high_priority" ? 15 : item.global_priority_band === "global_medium_priority" ? 8 : 0; const caution = safeLevel(item.jurisdiction_contact_caution); score += caution === "low" ? 10 : caution === "medium" ? 3 : caution === "high" ? -15 : 0; if (targetDecision === "approved") score += 10; if (first === "approved") score += 5; if (technical === "approved") score += 5; if (interest === "interested_in_technical_review") score += 10; if (interest === "interested_in_private_pilot") score += 15; score = stopped ? 0 : Math.max(0, Math.min(100, score));
  const rejection = !name ? "missing_or_unsafe_target_name" : targetDecision === "rejected" ? "target_rejected" : contactStatus === "do_not_contact" ? "do_not_contact" : requestedPilot === "approved" && !INTERESTED.has(interest) ? "pilot_follow_up_requires_recorded_interest" : null;
  const recommendedType = stopped ? "none" : targetApproved && INTERESTED.has(interest) && pilot !== "approved" ? "commercial_pilot_follow_up" : targetApproved && technical !== "approved" ? "technical_invitation" : targetApproved && first !== "approved" ? "educational_first_contact" : "none";
  return { queue_item_id: safeQueueItemId(item.queue_item_id ?? item.target_id ?? name ?? "rejected"), target_id: safeTargetId(item.target_id ?? name ?? "rejected"), target_name: name ?? "Rejected target", region: safeLabel(item.region, "unknown"), country_or_market: safeLabel(item.country_or_market, "unspecified_market"), target_category: safeLabel(item.target_category, "other"), likely_buyer_role: safeRole(item.likely_buyer_role), global_pilot_fit_score: fit, global_priority_band: safeGlobalBand(item.global_priority_band), jurisdiction_contact_caution: caution, outreach_queue_score: score, manual_review_priority: priority(score), gareth_target_decision: targetDecision, gareth_first_contact_decision: first, gareth_technical_invite_decision: technical, gareth_pilot_follow_up_decision: pilot, manual_contact_status: contactStatus, interest_status: interest, allowed_next_manual_step: stopped ? "No further contact or message action." : targetDecision !== "approved" ? "Gareth reviews the target decision." : recommendedType === "commercial_pilot_follow_up" ? "Gareth may review a local pilot follow-up draft because interest is recorded." : recommendedType === "technical_invitation" ? "Gareth may review a local technical invitation draft." : recommendedType === "educational_first_contact" ? "Gareth may review a local educational first-contact draft." : "No further message approval is currently required.", forbidden_next_steps: ["Automatic outreach", "Sending from this tool", "Contact without target and message approval", "Pilot follow-up without recorded interest", "Contact after rejection or do-not-contact"], recommended_message_type: recommendedType, recommended_manual_action: stopped ? "Keep blocked and do not contact." : targetDecision !== "approved" ? "Gareth reviews target suitability before any message." : "Gareth reviews the next local message decision; any contact remains outside this tool.", safety_notes: ["No message was sent by this tool", "No scraping or internet lookup occurred", "Jurisdiction caution requires manual review"], rejection_reason: rejection };
}

export function rankOutreachQueueItems(items: readonly ScoredOutreachQueueItem[]): ScoredOutreachQueueItem[] { return [...items].sort((a, b) => b.outreach_queue_score - a.outreach_queue_score || a.queue_item_id.localeCompare(b.queue_item_id)); }
export function createGarethManualOutreachApprovalQueueId(sourceId: string): string { return "gareth_manual_outreach_approval_queue_" + createHash("sha256").update(sourceId, "utf8").digest("hex").slice(0, 24); }
export function summariseGarethManualOutreachApprovalQueue(queue: GarethManualOutreachApprovalQueue): GarethManualOutreachApprovalQueueSummary { const { queue_items: _a, top_manual_review_items: _b, contact_policy: _c, approval_policy: _d, recommended_next_steps: _e, created_at: _f, ...summary } = queue; return summary; }
export function renderGarethManualOutreachApprovalQueueMarkdown(queue: GarethManualOutreachApprovalQueue): string { const section = (heading: string, values: readonly string[]) => [`## ${heading}`, ...(values.length ? values : ["None"]).map(value => `- ${value}`), ""]; return ["# Gareth Manual Outreach Approval Queue", "", "Local approval planning only. No scraping, searching, contact, email, or message has occurred inside this tool.", "", `## Queue Status\n${queue.queue_status}`, "", ...section("Approval Summary", Object.entries(queue.approval_summary).map(([key, value]) => `${key}: ${value}`)), ...section("Top Manual Review Items", queue.top_manual_review_items.map(item => `${item.target_name}: ${item.outreach_queue_score} (${item.manual_review_priority})`)), ...section("Queue Item Details", queue.queue_items.map(item => `${item.target_name}: target ${item.gareth_target_decision}; next ${item.allowed_next_manual_step}`)), ...section("Contact Policy", queue.contact_policy), ...section("Approval Rules", queue.approval_policy), ...section("Jurisdiction Contact Cautions", Object.entries(queue.jurisdiction_contact_caution_summary).map(([key, value]) => `${key}: ${value}`)), "## What Remains Disabled", "No public API, live agents, payment, billing, settlement, tracking, analytics, deployment, publishing, scraping, or action execution is enabled.", "", "## Gareth Approval Gate", "All contact is manual and outside this tool. Gareth approves every target and every message before contact.", "", ...section("Recommended Next Steps", queue.recommended_next_steps)].join("\n"); }
export function renderGarethManualOutreachApprovalQueueCsv(queue: GarethManualOutreachApprovalQueue): string { const headers = ["queue_item_id", "target_id", "target_name", "region", "country_or_market", "target_category", "likely_buyer_role", "global_pilot_fit_score", "global_priority_band", "jurisdiction_contact_caution", "outreach_queue_score", "manual_review_priority", "gareth_target_decision", "gareth_first_contact_decision", "gareth_technical_invite_decision", "gareth_pilot_follow_up_decision", "manual_contact_status", "interest_status", "recommended_message_type", "recommended_manual_action", "allowed_next_manual_step"] as const; return [headers.join(","), ...queue.queue_items.map(item => headers.map(header => csv(String(item[header]))).join(","))].join("\n"); }

function safeDecision(value: unknown): OutreachDecision { return typeof value === "string" && DECISIONS.has(value as OutreachDecision) ? value as OutreachDecision : "not_reviewed"; }
function safeContact(value: unknown): ManualContactStatus { return typeof value === "string" && CONTACT_STATUSES.has(value as ManualContactStatus) ? value as ManualContactStatus : "unknown"; }
function safeInterest(value: unknown): InterestStatus { return typeof value === "string" && INTEREST_STATUSES.has(value as InterestStatus) ? value as InterestStatus : "unknown"; }
function safeLevel(value: unknown): "low" | "medium" | "high" | "unknown" { return value === "low" || value === "medium" || value === "high" ? value : "unknown"; }
function effectiveMessageDecision(value: unknown, prerequisite: boolean, stopped: boolean): OutreachDecision { const decision = safeDecision(value); if (stopped) return decision === "rejected" ? "rejected" : "hold"; if (decision === "approved" && !prerequisite) return "hold"; return decision; }
function safeScore(value: unknown): number { return typeof value === "number" && Number.isFinite(value) ? Math.max(0, Math.min(100, value)) : 0; }
function priority(score: number): ManualReviewPriority { return score >= 85 ? "urgent_review" : score >= 70 ? "high_review" : score >= 50 ? "medium_review" : score >= 25 ? "low_review" : "not_recommended"; }
function safeName(value: unknown): string | null { if (typeof value !== "string") return null; const clean = value.trim().replace(/\s+/g, " ").slice(0, 80); return clean && !/[@<>]|https?:|www\./i.test(clean) ? clean : null; }
function safeLabel(value: unknown, fallback: string): string { if (typeof value !== "string") return fallback; const clean = value.trim().toLowerCase().replace(/[^a-z0-9 _-]/g, "").replace(/\s+/g, "_").slice(0, 48); return clean || fallback; }
function safeRole(value: unknown): string { const key = safeLabel(value, "technical_decision_maker"); return key.split("_").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" "); }
function safeGlobalBand(value: unknown): string { return value === "global_high_priority" || value === "global_medium_priority" || value === "global_low_priority" || value === "not_recommended" ? value : "not_recommended"; }
function safeQueueItemId(value: string): string { return "queue_item_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 16); }
function safeTargetId(value: string): string { return "target_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 16); }
function safeId(value: string): string { return "source_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 20); }
function safeTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "1970-01-01T00:00:00.000Z" : date.toISOString(); }
function count(values: readonly string[]): Record<string, number> { const result: Record<string, number> = {}; for (const value of values) result[value] = (result[value] ?? 0) + 1; return result; }
function nextSteps(status: OutreachQueueStatus, items: readonly ScoredOutreachQueueItem[]): string[] { if (status === "queue_blocked") return ["Do not contact any target", "Resolve prohibited capability or approval-order violations", "Rebuild the queue locally"]; if (status === "queue_ready_for_gareth_review") return ["Gareth reviews ranked targets and effective message decisions", "Keep actual contact outside this tool", "Record interest before considering pilot follow-up", "Respect rejection and do-not-contact records"]; return items.length ? ["Gareth reviews target decisions", "Keep every message and contact action disabled"] : ["Add manually supplied placeholder queue items", "Do not search or scrape for targets"]; }
function csv(value: string): string { return `"${value.replace(/"/g, '""').replace(/[\r\n]/g, " ")}"`; }
