import { readFileSync } from "node:fs";
import { createGarethManualOutreachApprovalQueue, renderGarethManualOutreachApprovalQueueCsv, renderGarethManualOutreachApprovalQueueMarkdown, type GarethManualOutreachApprovalQueueInput } from "./gareth-manual-outreach-approval-queue.js";
export type OutreachQueueCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "EMPTY_QUEUE_ITEMS" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "QUEUE_ERROR";
export interface OutreachQueueCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: OutreachQueueCliErrorCode, message: string) { super(message); } }
const defaultIo: OutreachQueueCliIo = { stdout: console.log, stderr: console.error };
export function runGarethManualOutreachApprovalQueueCli(args: readonly string[], io: OutreachQueueCliIo = defaultIo): number { try { const options = parse(args), queue = createGarethManualOutreachApprovalQueue(readGarethManualOutreachApprovalQueueInput(options.path)); io.stdout(options.mode === "markdown" ? renderGarethManualOutreachApprovalQueueMarkdown(queue) : options.mode === "csv" ? renderGarethManualOutreachApprovalQueueCsv(queue) : JSON.stringify(queue, null, options.pretty ? 2 : 0)); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readGarethManualOutreachApprovalQueueInput(path: string): GarethManualOutreachApprovalQueueInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local approval-queue input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local approval-queue input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const record = value as Record<string, unknown>; if (typeof record.educational_review_pack_result !== "object" || record.educational_review_pack_result === null || Array.isArray(record.educational_review_pack_result)) throw invalid("Missing educational_review_pack_result."); if (!Array.isArray(record.queue_items)) throw invalid("Missing queue_items."); if (record.queue_items.length === 0) throw new CliError("EMPTY_QUEUE_ITEMS", "At least one manually supplied queue item is required by the CLI."); if (typeof record.source_id !== "string" || typeof record.created_at !== "string") throw invalid("Missing required local metadata."); return record as unknown as GarethManualOutreachApprovalQueueInput; }
function parse(args: readonly string[]) { let path: string | undefined; let pretty = false; let mode: "json" | "markdown" | "csv" = "json"; let selected = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = arg === "--markdown" ? "markdown" : arg === "--csv" ? "csv" : undefined; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported approval-queue option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "QUEUE_ERROR", message: known ? error.message : "The local approval queue could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, no_email_sent: true, no_message_sent: true, no_automatic_contact: true, no_scraping_performed: true, no_external_lookup_performed: true, status: "approval_queue_only" }; }
if (process.argv[1]?.endsWith("gareth-manual-outreach-approval-queue-cli.js")) process.exitCode = runGarethManualOutreachApprovalQueueCli(process.argv.slice(2));
