import { readFileSync } from "node:fs";
import { createGarethGlobalLaunchApproval, renderGarethGlobalLaunchApprovalMarkdown, renderPostUploadVerificationChecklistMarkdown, renderPreUploadChecklistMarkdown, renderRollbackChecklistMarkdown, renderStaticUploadInstructionsMarkdown, type GarethGlobalLaunchApprovalInput } from "./gareth-global-launch-approval.js";
export type GarethGlobalLaunchApprovalCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "LAUNCH_APPROVAL_ERROR";
export interface GarethGlobalLaunchApprovalCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: GarethGlobalLaunchApprovalCliErrorCode, message: string) { super(message); } }
const defaultIo: GarethGlobalLaunchApprovalCliIo = { stdout: console.log, stderr: console.error };
export function runGarethGlobalLaunchApprovalCli(args: readonly string[], io: GarethGlobalLaunchApprovalCliIo = defaultIo): number { try { const options = parse(args), approval = createGarethGlobalLaunchApproval(readGarethGlobalLaunchApprovalInput(options.path)); const output = options.mode === "approval" ? renderGarethGlobalLaunchApprovalMarkdown(approval) : options.mode === "upload" ? renderStaticUploadInstructionsMarkdown(approval) : options.mode === "pre" ? renderPreUploadChecklistMarkdown(approval) : options.mode === "post" ? renderPostUploadVerificationChecklistMarkdown(approval) : options.mode === "rollback" ? renderRollbackChecklistMarkdown(approval) : JSON.stringify(approval, null, options.pretty ? 2 : 0); io.stdout(output); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readGarethGlobalLaunchApprovalInput(path: string): GarethGlobalLaunchApprovalInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local launch-approval input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local launch-approval input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const r = value as Record<string, unknown>; if (typeof r.owner_decision !== "string") throw invalid("Missing owner_decision."); if (typeof r.owner_confirmation !== "boolean") throw invalid("Missing owner_confirmation."); if (typeof r.launch_folder_result !== "object" || r.launch_folder_result === null || Array.isArray(r.launch_folder_result)) throw invalid("Missing launch_folder_result."); if (typeof r.source_id !== "string" || typeof r.created_at !== "string") throw invalid("Missing required local metadata."); return r as unknown as GarethGlobalLaunchApprovalInput; }
function parse(args: readonly string[]) { let path: string | undefined, pretty = false, mode: "json" | "approval" | "upload" | "pre" | "post" | "rollback" = "json", selected = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = arg === "--approval-markdown" ? "approval" : arg === "--upload-instructions" ? "upload" : arg === "--pre-upload-checklist" ? "pre" : arg === "--post-upload-checklist" ? "post" : arg === "--rollback-checklist" ? "rollback" : undefined; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported launch-approval option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "LAUNCH_APPROVAL_ERROR", message: known ? error.message : "The local launch approval could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, live_agent_access_enabled: false, backend_required: false, endpoint_created: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "launch_approval_only" }; }
if (process.argv[1]?.endsWith("gareth-global-launch-approval-cli.js")) process.exitCode = runGarethGlobalLaunchApprovalCli(process.argv.slice(2));
