import { createHash } from "node:crypto";
import { createAgentToAgentDiscoveryPack, renderAgentCardJson, renderAgentReadableOfferJson, renderCapabilitiesJson, renderDisabledCapabilitiesJson, renderHumanApprovalPolicyJson, renderLlmsTxt, renderPricingPilotMetadataJson, renderPrivatePilotManifestJson, renderTechnicalReviewJson } from "./agent-to-agent-discovery-pack.js";

export const GLOBAL_DISCOVERY_LIVE_LAUNCH_FOLDER_VERSION = "atg.global-discovery-live-launch-folder.v1" as const;
export type GlobalDiscoveryLaunchStatus = "global_discovery_launch_folder_ready" | "launch_folder_hold" | "launch_folder_blocked" | "unknown";
export interface GlobalDiscoveryLiveLaunchFolderInput { [key: string]: unknown; launch_folder_id?: string; source_id: string; product_name?: string; owner_name?: string; agent_to_agent_discovery_pack_result?: Record<string, unknown>; educational_review_pack_result?: Record<string, unknown>; pilot_offer_result?: Record<string, unknown>; launch_domain_placeholder?: string; safety_flags?: Record<string, unknown>; created_at: string }
export interface GlobalDiscoveryLaunchFile { path: string; content_type: string }
export interface GlobalDiscoveryLiveLaunchFolder { launch_folder_id: string; launch_folder_type: "static_global_discovery_launch_folder"; source_id: string; product_name: "Agent Trust Gate™"; owner_name: "Gareth"; launch_status: GlobalDiscoveryLaunchStatus; folder_path: "global-discovery-launch"; file_count: number; files: GlobalDiscoveryLaunchFile[]; static_launch_ready: boolean; upload_ready_after_gareth_approval: boolean; public_discovery_supported: true; machine_readable_discovery_supported: true; human_readable_discovery_supported: true; agent_card_included: true; llms_txt_included: true; offer_json_included: true; technical_review_json_included: true; capabilities_json_included: true; disabled_capabilities_json_included: true; private_pilot_manifest_included: true; human_approval_policy_included: true; pricing_metadata_included: true; launch_boundaries_included: true; quantum_readiness_included: true; public_api_enabled: false; live_agent_access_enabled: false; backend_required: false; endpoint_created: false; payment_enabled: false; tracking_enabled: false; analytics_enabled: false; action_execution_enabled: false; gareth_approval_required_before_upload: true; gareth_approval_required_before_domain_connection: true; recommended_hosting_options: string[]; recommended_next_steps: string[]; plain_english_summary: string; private_data_included: false; network_lookup_performed: false; external_lookup_performed: false; tracking_triggered: false; analytics_triggered: false; payment_or_fee_triggered: false; billing_triggered: false; settlement_triggered: false; machine_to_machine_fee_triggered: false; action_executed: false; email_sent: false; message_sent: false; scraped: false; deployed: false; published: false; status: "launch_folder_only"; created_at: string }
export type GlobalDiscoveryLiveLaunchFolderSummary = Pick<GlobalDiscoveryLiveLaunchFolder, "launch_folder_id" | "launch_status" | "folder_path" | "file_count" | "static_launch_ready" | "upload_ready_after_gareth_approval" | "public_api_enabled" | "live_agent_access_enabled" | "backend_required" | "endpoint_created" | "payment_enabled" | "tracking_enabled" | "analytics_enabled" | "action_execution_enabled" | "deployed" | "published" | "plain_english_summary" | "status">;

const FOLDER = "global-discovery-launch" as const;
const FILE_TYPES: ReadonlyArray<readonly [string, string]> = [["index.html", "text/html"], ["llms.txt", "text/plain"], [".well-known/agent.json", "application/json"], ["agent-trust-gate-offer.json", "application/json"], ["technical-review.json", "application/json"], ["capabilities.json", "application/json"], ["disabled-capabilities.json", "application/json"], ["private-pilot-manifest.json", "application/json"], ["human-approval-policy.json", "application/json"], ["pricing-pilot-metadata.json", "application/json"], ["README.md", "text/markdown"], ["robots.txt", "text/plain"], ["sitemap.xml", "application/xml"], ["launch-boundaries.json", "application/json"], ["quantum-readiness.json", "application/json"]];
const BLOCKED_FLAGS = ["public_api_enabled", "live_endpoint_enabled", "endpoint_created", "backend_required", "real_external_agents_enabled", "live_agent_access_enabled", "deployed", "published", "payment_enabled", "billing_enabled", "settlement_enabled", "machine_to_machine_fee_enabled", "tracking_enabled", "analytics_enabled", "action_execution_enabled", "private_data_included", "real_url_included", "credentials_included", "payment_link_included", "quantum_security_claimed", "post_quantum_compliance_claimed", "legal_certification_claimed", "scraping_enabled", "internet_search_enabled", "email_sending_enabled", "message_sending_enabled"] as const;

export function createGlobalDiscoveryLiveLaunchFolder(input: GlobalDiscoveryLiveLaunchFolderInput): GlobalDiscoveryLiveLaunchFolder {
  const flags = input.safety_flags ?? {};
  const blocked = BLOCKED_FLAGS.some(key => flags[key] === true) || (typeof input.launch_domain_placeholder === "string" && input.launch_domain_placeholder !== "example.invalid");
  const discoveryReady = input.agent_to_agent_discovery_pack_result?.discovery_status === "discovery_pack_ready";
  const complete = discoveryReady && input.launch_domain_placeholder === "example.invalid";
  const launchStatus: GlobalDiscoveryLaunchStatus = blocked ? "launch_folder_blocked" : complete ? "global_discovery_launch_folder_ready" : "launch_folder_hold";
  const ready = launchStatus === "global_discovery_launch_folder_ready";
  return { launch_folder_id: createGlobalDiscoveryLaunchFolderId(input.launch_folder_id ?? input.source_id), launch_folder_type: "static_global_discovery_launch_folder", source_id: safeId(input.source_id), product_name: "Agent Trust Gate™", owner_name: "Gareth", launch_status: launchStatus, folder_path: FOLDER, file_count: FILE_TYPES.length, files: FILE_TYPES.map(([path, content_type]) => ({ path, content_type })), static_launch_ready: ready, upload_ready_after_gareth_approval: ready, public_discovery_supported: true, machine_readable_discovery_supported: true, human_readable_discovery_supported: true, agent_card_included: true, llms_txt_included: true, offer_json_included: true, technical_review_json_included: true, capabilities_json_included: true, disabled_capabilities_json_included: true, private_pilot_manifest_included: true, human_approval_policy_included: true, pricing_metadata_included: true, launch_boundaries_included: true, quantum_readiness_included: true, public_api_enabled: false, live_agent_access_enabled: false, backend_required: false, endpoint_created: false, payment_enabled: false, tracking_enabled: false, analytics_enabled: false, action_execution_enabled: false, gareth_approval_required_before_upload: true, gareth_approval_required_before_domain_connection: true, recommended_hosting_options: ["Cloudflare Pages", "GitHub Pages", "Netlify", "Existing Braylock site when static upload and .well-known support are available"], recommended_next_steps: ready ? ["Gareth reviews every generated static file", "Obtain Gareth approval before upload", "Obtain separate Gareth approval before connecting a domain"] : ["Resolve the local hold or blocked condition", "Keep the folder local and unpublished"], plain_english_summary: ready ? "The static global discovery folder is ready for Gareth review and a future approved upload. It does not expose an engine, API, endpoint, payment rail, tracking, or action execution." : launchStatus === "launch_folder_blocked" ? "The launch folder is blocked by a prohibited live, private, commercial, deployment, or certification condition. Nothing was uploaded or published." : "The launch folder is on hold until the local discovery pack and example.invalid placeholder are available. Nothing was uploaded or published.", private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "launch_folder_only", created_at: safeTime(input.created_at) };
}

export function buildGlobalDiscoveryLaunchFiles(input: GlobalDiscoveryLiveLaunchFolderInput): Record<string, string> {
  const result = createGlobalDiscoveryLiveLaunchFolder(input);
  const pack = createAgentToAgentDiscoveryPack({ source_id: input.source_id, created_at: input.created_at, educational_review_pack_result: { review_status: input.educational_review_pack_result?.review_status === "educational_review_pack_ready" ? "educational_review_pack_ready" : "educational_review_pack_ready" }, manual_outreach_approval_queue_result: { queue_status: input.agent_to_agent_discovery_pack_result?.discovery_status === "discovery_pack_ready" ? "queue_ready_for_gareth_review" : "queue_hold" }, pilot_offer_result: { commercial_status: input.pilot_offer_result?.commercial_status === "draft_private_pilot_offer_ready" ? "draft_private_pilot_offer_ready" : "draft_private_pilot_offer_ready" } });
  return { "index.html": renderGlobalDiscoveryIndexHtml(result), "llms.txt": renderLaunchLlmsTxt(pack.llms_txt), ".well-known/agent.json": renderAgentCardJson(pack), "agent-trust-gate-offer.json": renderAgentReadableOfferJson(pack), "technical-review.json": renderTechnicalReviewJson(pack), "capabilities.json": renderCapabilitiesJson(pack), "disabled-capabilities.json": renderDisabledCapabilitiesJson(pack), "private-pilot-manifest.json": renderPrivatePilotManifestJson(pack), "human-approval-policy.json": renderHumanApprovalPolicyJson(pack), "pricing-pilot-metadata.json": renderPricingPilotMetadataJson(pack), "README.md": renderGlobalDiscoveryReadme(result), "robots.txt": renderGlobalDiscoveryRobotsTxt(result), "sitemap.xml": renderGlobalDiscoverySitemapXml(result), "launch-boundaries.json": renderGlobalDiscoveryLaunchBoundariesJson(result), "quantum-readiness.json": renderGlobalDiscoveryQuantumReadinessJson(result) };
}

export function createGlobalDiscoveryLaunchFolderId(sourceId: string): string { return "global_discovery_launch_folder_" + createHash("sha256").update(sourceId, "utf8").digest("hex").slice(0, 24); }
export function summariseGlobalDiscoveryLiveLaunchFolder(result: GlobalDiscoveryLiveLaunchFolder): GlobalDiscoveryLiveLaunchFolderSummary { const { launch_folder_id, launch_status, folder_path, file_count, static_launch_ready, upload_ready_after_gareth_approval, public_api_enabled, live_agent_access_enabled, backend_required, endpoint_created, payment_enabled, tracking_enabled, analytics_enabled, action_execution_enabled, deployed, published, plain_english_summary, status } = result; return { launch_folder_id, launch_status, folder_path, file_count, static_launch_ready, upload_ready_after_gareth_approval, public_api_enabled, live_agent_access_enabled, backend_required, endpoint_created, payment_enabled, tracking_enabled, analytics_enabled, action_execution_enabled, deployed, published, plain_english_summary, status }; }
export function renderGlobalDiscoveryIndexHtml(_result: GlobalDiscoveryLiveLaunchFolder): string { return `<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agent Trust Gate™</title><style>body{font-family:system-ui,sans-serif;max-width:52rem;margin:auto;padding:2rem;line-height:1.55}code{background:#eee;padding:.1rem .25rem}a{color:#0645ad}</style></head>\n<body><main><h1>Agent Trust Gate™</h1><p><strong>Pre-action clearing for AI agents before they access data, spend money, call tools, or trigger external actions.</strong></p><p>This static, education-first technical review explains a private fake-agent pilot route without exposing a live engine.</p><h2>Machine-readable discovery</h2><ul><li><a href="llms.txt">llms.txt</a></li><li><a href=".well-known/agent.json">Agent card</a></li><li><a href="capabilities.json">Capabilities</a></li><li><a href="disabled-capabilities.json">Disabled capabilities</a></li><li><a href="technical-review.json">Technical review</a></li><li><a href="agent-trust-gate-offer.json">Private pilot offer</a></li></ul><h2>Available</h2><p>Static descriptions, local fake-agent sandbox concepts, entitlement and allow/deny gates, receipts, evidence, replay, and human approval policy.</p><h2>Disabled</h2><p>No public API, live endpoint, real external agents, payment, billing, settlement, tracking, analytics, or action execution.</p><h2>Approval boundary</h2><p>Gareth approval is required before upload, domain connection, external sharing, or any future live access.</p><h2>Quantum readiness</h2><p>Positioning only. No quantum-security or post-quantum-compliance claim is made. This is not legal, compliance, or audit certification.</p></main></body>\n</html>\n`; }
export function renderGlobalDiscoveryReadme(_result: GlobalDiscoveryLiveLaunchFolder): string { return `# Global Discovery Live Launch Folder\n\nStatic upload-ready discovery files only. Upload only after Gareth approval.\n\nThere is no backend, public API, live engine access, payment, tracking, or action execution.\n\n## Hosting review options\n\n- Cloudflare Pages\n- GitHub Pages\n- Netlify\n- Existing Braylock site when static upload and .well-known support are available\n\nNo publishing or domain connection is authorised by this folder.\n`; }
export function renderGlobalDiscoveryRobotsTxt(_result: GlobalDiscoveryLiveLaunchFolder): string { return "User-agent: *\nAllow: /\n\nSitemap: https://example.invalid/sitemap.xml\n"; }
export function renderGlobalDiscoverySitemapXml(_result: GlobalDiscoveryLiveLaunchFolder): string { const paths = ["/", "/llms.txt", "/.well-known/agent.json", "/agent-trust-gate-offer.json", "/technical-review.json", "/capabilities.json", "/disabled-capabilities.json", "/private-pilot-manifest.json", "/human-approval-policy.json", "/pricing-pilot-metadata.json"]; return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset>\n${paths.map(path => `  <url><loc>https://example.invalid${path}</loc></url>`).join("\n")}\n</urlset>\n`; }
export function renderGlobalDiscoveryLaunchBoundariesJson(_result: GlobalDiscoveryLiveLaunchFolder): string { return pretty({ public_api_enabled: false, live_agent_access_enabled: false, backend_required: false, endpoint_created: false, real_external_agents_enabled: false, payment_enabled: false, billing_enabled: false, settlement_enabled: false, tracking_enabled: false, analytics_enabled: false, action_execution_enabled: false, deployment_requires_gareth_approval: true, domain_connection_requires_gareth_approval: true, private_pilot_requires_gareth_approval: true }); }
export function renderGlobalDiscoveryQuantumReadinessJson(_result: GlobalDiscoveryLiveLaunchFolder): string { return pretty({ quantum_claim_level: "positioning_only", quantum_security_claimed: false, post_quantum_compliance_claimed: false, nist_certification_claimed: false, ml_kem_implemented: false, ml_dsa_implemented: false, slh_dsa_implemented: false, production_crypto_change: false, future_pqc_migration_awareness: true, cryptographic_inventory_readiness_placeholders: true }); }
function renderLaunchLlmsTxt(base: string): string { return `${base.trim()}\n\n## Static discovery files\nAgent card, offer, technical review, capabilities, disabled capabilities, pilot manifest, human approval policy, pricing metadata, launch boundaries, and quantum-readiness positioning are available as static files.\n\n## Private pilot route\nA fake-agent private pilot may be reviewed only after Gareth approval. No production API or live endpoint exists.\n`; }
function pretty(value: unknown): string { return JSON.stringify(value, null, 2) + "\n"; }
function safeId(value: string): string { return "source_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 20); }
function safeTime(value: string): string { const time = new Date(value); return Number.isNaN(time.valueOf()) ? "1970-01-01T00:00:00.000Z" : time.toISOString(); }
