import { createHash } from "node:crypto";

export const GLOBAL_EDUCATIONAL_TECHNICAL_REVIEW_PACK_VERSION = "atg.global-educational-technical-review-pack.v1" as const;
export type EducationalReviewStatus = "educational_review_pack_ready" | "educational_review_pack_hold" | "educational_review_pack_blocked" | "unknown";
export type QuantumClaimLevel = "none" | "positioning_only" | "readiness_inventory_only" | "future_roadmap_only";
export interface GlobalEducationalTechnicalReviewPackInput { [key: string]: unknown; review_pack_id?: string; source_id: string; product_name?: string; owner_name?: string; offer_pack_result?: Record<string, unknown>; target_list_result?: Record<string, unknown>; global_target_expansion_result?: Record<string, unknown>; review_positioning?: unknown; contact_policy?: Record<string, unknown>; quantum_readiness_policy?: Record<string, unknown>; safety_flags?: Record<string, unknown>; created_at: string }
export interface AgentReadableEducationalReview { review_type: "global_educational_technical_learning_review"; product_name: "Agent Trust Gate™"; technical_learning_objective: string; sandbox_scope: string[]; supported_review_topics: string[]; disabled_capabilities: string[]; required_approvals: string[]; quantum_claim_level: "positioning_only"; quantum_readiness_statement: string; commercial_follow_up_policy: string; next_step: string }
export interface GlobalEducationalTechnicalReviewPack {
  review_pack_id: string; review_pack_type: "global_educational_technical_review"; source_id: string; product_name: "Agent Trust Gate™"; owner_name: "Gareth"; review_status: EducationalReviewStatus;
  education_first_positioning: string; non_sales_positioning: string; technical_learning_objective: string; target_audience: string[]; ideal_review_participants: string[]; disqualified_participants: string[]; developer_value_proposition: string[]; agent_platform_value_proposition: string[]; governance_value_proposition: string[]; security_value_proposition: string[]; quantum_readiness_value_proposition: string[]; technical_review_scope: string[]; technical_review_deliverables: string[]; technical_feedback_questions: string[]; qualification_questions: string[];
  educational_first_contact_message: string; technical_feedback_invitation: string; commercial_pilot_follow_up_message: string; agent_readable_review_json: AgentReadableEducationalReview; global_contact_caution_notes: string[]; opt_out_wording_draft: string; what_the_review_proves: string[]; what_the_review_does_not_prove: string[]; what_remains_disabled: string[];
  gareth_approval_required_before_sending: true; manual_contact_only: true; no_automatic_outreach: true; no_scraping_performed: true; no_external_lookup_performed: true; quantum_readiness_statement: string; post_quantum_readiness_statement: string; quantum_claim_level: "positioning_only"; quantum_claims_not_made: string[]; cryptographic_inventory_readiness: string[]; future_pqc_migration_awareness: string[]; plain_english_summary: string; recommended_next_steps: string[];
  private_data_included: false; network_lookup_performed: false; external_lookup_performed: false; public_api_enabled: false; tracking_triggered: false; analytics_triggered: false; payment_or_fee_triggered: false; billing_triggered: false; settlement_triggered: false; machine_to_machine_fee_triggered: false; action_executed: false; email_sent: false; message_sent: false; scraped: false; deployed: false; published: false; status: "educational_review_pack_only"; created_at: string;
}
export type GlobalEducationalTechnicalReviewPackSummary = Pick<GlobalEducationalTechnicalReviewPack, "review_pack_id" | "review_status" | "product_name" | "quantum_claim_level" | "gareth_approval_required_before_sending" | "manual_contact_only" | "no_automatic_outreach" | "no_scraping_performed" | "no_external_lookup_performed" | "plain_english_summary" | "private_data_included" | "network_lookup_performed" | "external_lookup_performed" | "public_api_enabled" | "tracking_triggered" | "analytics_triggered" | "payment_or_fee_triggered" | "billing_triggered" | "settlement_triggered" | "machine_to_machine_fee_triggered" | "action_executed" | "email_sent" | "message_sent" | "scraped" | "deployed" | "published" | "status">;

const EDUCATION = "An educational technical review of pre-action clearing for AI agents before they access data, spend money, call tools, or trigger external actions.";
const OBJECTIVE = "To understand how agent platforms and AI systems think about permission, entitlement, evidence, refusal signals, receipts, replay, and pre-action risk checks before agents act.";
const NON_SALES = "This is an invitation to review the technical concept and provide feedback. It is not a public launch, production API, legal/compliance certification, or request to integrate real agents.";
const QUANTUM = "Agent Trust Gate™ is not a quantum cryptography product and does not claim post-quantum security. The current educational review pack includes future-readiness language for cryptographic inventory, evidence trails, and post-quantum migration awareness only.";
const POST_QUANTUM = "Future versions may include a cryptographic inventory and post-quantum migration readiness checklist for agent/system integrations. This release does not implement ML-KEM, ML-DSA, SLH-DSA, or any production post-quantum cryptographic controls.";
const DISABLED = ["Public API and network access", "Real agents, production integrations, and real customer data", "Payment, billing, settlement, invoices, and live machine fees", "Tracking, analytics, scraping, lead harvesting, and automatic outreach", "Deployment, publishing, webhooks, and action execution", "Quantum cryptography and production post-quantum controls"];
const BLOCKED_FLAGS = ["automatic_outreach_enabled", "scraping_enabled", "external_lookup_enabled", "network_lookup_enabled", "email_sending_enabled", "message_sending_enabled", "public_api_enabled", "payment_enabled", "billing_enabled", "settlement_enabled", "tracking_enabled", "analytics_enabled", "deployment_enabled", "publishing_enabled", "action_execution_enabled", "private_data_included", "quantum_certification_claimed", "post_quantum_compliance_claimed", "legal_certification_claimed", "compliance_certification_claimed", "audit_certification_claimed"] as const;

export function createGlobalEducationalTechnicalReviewPack(input: GlobalEducationalTechnicalReviewPackInput): GlobalEducationalTechnicalReviewPack {
  const safety = input.safety_flags ?? {}, contact = input.contact_policy ?? {}, quantumPolicy = input.quantum_readiness_policy ?? {};
  const blocked = BLOCKED_FLAGS.some(key => safety[key] === true || contact[key] === true || quantumPolicy[key] === true);
  const offerReady = input.offer_pack_result?.commercial_status === "draft_private_pilot_offer_ready";
  const targetReady = input.target_list_result?.commercial_status === "target_list_ready_for_gareth_review" || input.global_target_expansion_result?.commercial_status === "target_list_ready_for_gareth_review";
  const complete = Boolean(input.offer_pack_result && input.target_list_result && (offerReady || targetReady));
  const reviewStatus: EducationalReviewStatus = blocked ? "educational_review_pack_blocked" : complete ? "educational_review_pack_ready" : "educational_review_pack_hold";
  const firstContact = "Hi [Name], I’m conducting a private technical learning review for Agent Trust Gate™, a pre-action clearing concept for AI agents before they access data, spend money, call tools, or trigger external actions. The current demo is local and fake-agent only, covering allow/deny decisions, entitlement checks, refusal signals, receipts, evidence bundles, and replay. Would your team be open to reviewing the concept and sharing technical feedback?";
  const technicalInvite = "This private technical feedback invitation uses a local fake-agent sandbox to review pre-action clearance, entitlement checks, allow/deny gates, RefusalGraph-style refusal intelligence, receipts, evidence bundles, replay, a human approval gate, and excessive-agency boundaries. Future quantum-readiness is awareness only. There is no production API, real money movement, or live action execution.";
  const pilotFollowUp = "After interest is shown: thank you for reviewing the concept. If useful, we could discuss a scope-limited private sandbox pilot using fake/test agents only, with no production integration, real customer data, live payment, or action execution. Commercial terms would be discussed only after mutual fit and Gareth approval.";
  const reviewJson: AgentReadableEducationalReview = { review_type: "global_educational_technical_learning_review", product_name: "Agent Trust Gate™", technical_learning_objective: OBJECTIVE, sandbox_scope: ["Local fake-agent sandbox only", "Synthetic inputs and deterministic local outputs", "No production or external integration"], supported_review_topics: ["Pre-action permission and entitlement", "Allow, deny, and human approval gates", "Refusal signals, receipts, evidence bundles, and replay", "Excessive-agency boundaries", "Future cryptographic inventory and PQC migration awareness"], disabled_capabilities: [...DISABLED], required_approvals: ["Gareth approval for every target", "Gareth approval for every message", "Separate approval before any commercial follow-up"], quantum_claim_level: "positioning_only", quantum_readiness_statement: QUANTUM, commercial_follow_up_policy: "Only after expressed interest, mutual fit, and separate Gareth approval; no payment collection is enabled.", next_step: reviewStatus === "educational_review_pack_ready" ? "Gareth manually reviews one placeholder target and one local message draft." : "Hold all contact until local readiness and safety checks pass." };
  return {
    review_pack_id: createGlobalEducationalTechnicalReviewPackId(input.review_pack_id ?? input.source_id), review_pack_type: "global_educational_technical_review", source_id: safeId(input.source_id), product_name: "Agent Trust Gate™", owner_name: "Gareth", review_status: reviewStatus,
    education_first_positioning: EDUCATION, non_sales_positioning: NON_SALES, technical_learning_objective: OBJECTIVE,
    target_audience: ["AI agent developers", "AI platform builders", "Workflow automation companies", "Enterprise AI governance teams", "AI security teams", "Procurement and finance automation teams", "Agent protocol and marketplace builders", "Future post-quantum-readiness-aware infrastructure teams"], ideal_review_participants: ["Can evaluate a local fake-agent sandbox", "Has experience with agent permissions, tools, governance, or security", "Can provide technical feedback without requiring production access"], disqualified_participants: ["Requires immediate production integration", "Requires real agents, customer data, or action execution", "Requires safety, legal, compliance, audit, quantum, or PQC certification claims"],
    developer_value_proposition: ["Shows a clear pre-action gate pattern", "Provides a receipt and replay model for agent actions", "Offers fake-agent sandbox learning", "Helps explore agent permission boundaries"], agent_platform_value_proposition: ["Checks agent intent before tools or actions", "Supports allow, deny, and approval-gate thinking", "Provides evidence-bundle and replay language", "Explores a future clearing layer for agent-to-agent systems"], governance_value_proposition: ["Supports audit-style evidence trails without claiming certification", "Demonstrates refusal and denial reasoning", "Keeps human approval boundaries visible"], security_value_proposition: ["Highlights excessive-agency controls", "Makes failed and denied scenarios reviewable", "Keeps network, payment, and execution capabilities disabled"], quantum_readiness_value_proposition: ["Encourages a future cryptographic inventory", "Identifies future PQC migration touchpoints", "Makes no quantum-security or compliance claim"],
    technical_review_scope: ["Local fake-agent pre-action clearing demonstration", "Permission, entitlement, refusal, receipt, evidence, and replay review", "Human approval and excessive-agency boundary review", "Future cryptographic inventory awareness only"], technical_review_deliverables: ["Developer-focused technical brief", "Agent-readable review JSON", "Local fake-agent scenario outputs", "Technical feedback and qualification questions"], technical_feedback_questions: ["Where should a pre-action gate sit in your agent architecture?", "Which actions need entitlement or human approval?", "What evidence should an agent receipt preserve?", "How should refusal intelligence influence a later request?", "What replay information would help diagnose an agent decision?", "Which excessive-agency failures should a sandbox demonstrate?"], qualification_questions: ["Can the review use fake/test agents and synthetic data only?", "Which technical role would review the concept?", "Which permission, tool, data, spend, or external-action boundary matters?", "Is the first step educational feedback rather than integration?"],
    educational_first_contact_message: firstContact, technical_feedback_invitation: technicalInvite, commercial_pilot_follow_up_message: pilotFollowUp, agent_readable_review_json: reviewJson,
    global_contact_caution_notes: ["Educational framing must be honest and must not disguise a sales message", "A message promoting a commercial pilot may still be treated as marketing", "Different countries have different contact rules", "Corporate contact rules differ from personal contact rules", "Personal data must not be copied into this tool", "Opt-out and identity wording may be required", "Gareth must manually review every target and every message", "Legal review may be needed before scaled outreach", "These notes are not legal advice"], opt_out_wording_draft: "If this is not relevant, please ignore this message or let me know and I will not contact you again about this review.",
    what_the_review_proves: ["A local fake-agent learning review can demonstrate pre-action gate concepts", "Reviewers can inspect deterministic allow, deny, evidence, and replay outputs"], what_the_review_does_not_prove: ["Production readiness or guaranteed safety", "Legal, compliance, audit, security, quantum, or post-quantum certification", "Live agent, network, payment, or execution capability"], what_remains_disabled: [...DISABLED],
    gareth_approval_required_before_sending: true, manual_contact_only: true, no_automatic_outreach: true, no_scraping_performed: true, no_external_lookup_performed: true, quantum_readiness_statement: QUANTUM, post_quantum_readiness_statement: POST_QUANTUM, quantum_claim_level: "positioning_only", quantum_claims_not_made: ["Not quantum secure", "Not post-quantum compliant", "Not NIST certified", "Not legal, compliance, or audit certified", "Not an encryption provider", "Not a payment provider", "Not a production security guarantee"], cryptographic_inventory_readiness: ["Identify external endpoints in future integrations", "Identify cryptographic dependencies in future integrations", "Identify signing and verification mechanisms in future integrations", "Identify receipt integrity mechanisms in future integrations", "Identify data-retention and evidence-retention requirements", "Identify future PQC migration touchpoints", "Require specialist cryptographic review before production use"], future_pqc_migration_awareness: ["Inventory future integration cryptography", "Track future migration touchpoints", "Obtain specialist review before selecting or deploying cryptographic controls"],
    plain_english_summary: reviewStatus === "educational_review_pack_ready" ? "A global education-first technical review pack is ready for Gareth's local review. Nothing has been searched, scraped, contacted, emailed, messaged, published, deployed, billed, or executed." : reviewStatus === "educational_review_pack_blocked" ? "The educational review pack is blocked because a prohibited live, outreach, private-data, or certification condition was requested. Nothing was sent." : "The educational review pack is on hold until the offer and target readiness inputs are complete. Nothing was sent.", recommended_next_steps: reviewStatus === "educational_review_pack_ready" ? ["Gareth reviews the educational framing and technical questions", "Select one placeholder target for a separate local draft", "Obtain Gareth approval before any message is shared", "Keep any commercial follow-up separate and interest-led"] : ["Resolve missing or blocked readiness conditions", "Keep all contact and external activity disabled"],
    private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, status: "educational_review_pack_only", created_at: safeTime(input.created_at)
  };
}

export function createGlobalEducationalTechnicalReviewPackId(sourceId: string): string { return "global_educational_technical_review_pack_" + createHash("sha256").update(sourceId, "utf8").digest("hex").slice(0, 24); }
export function summariseGlobalEducationalTechnicalReviewPack(pack: GlobalEducationalTechnicalReviewPack): GlobalEducationalTechnicalReviewPackSummary { const { review_pack_id, review_status, product_name, quantum_claim_level, gareth_approval_required_before_sending, manual_contact_only, no_automatic_outreach, no_scraping_performed, no_external_lookup_performed, plain_english_summary, private_data_included, network_lookup_performed, external_lookup_performed, public_api_enabled, tracking_triggered, analytics_triggered, payment_or_fee_triggered, billing_triggered, settlement_triggered, machine_to_machine_fee_triggered, action_executed, email_sent, message_sent, scraped, deployed, published, status } = pack; return { review_pack_id, review_status, product_name, quantum_claim_level, gareth_approval_required_before_sending, manual_contact_only, no_automatic_outreach, no_scraping_performed, no_external_lookup_performed, plain_english_summary, private_data_included, network_lookup_performed, external_lookup_performed, public_api_enabled, tracking_triggered, analytics_triggered, payment_or_fee_triggered, billing_triggered, settlement_triggered, machine_to_machine_fee_triggered, action_executed, email_sent, message_sent, scraped, deployed, published, status }; }
export function renderGlobalEducationalTechnicalReviewJson(pack: GlobalEducationalTechnicalReviewPack): string { return JSON.stringify(pack.agent_readable_review_json, null, 2); }
export function renderEducationalFirstContactMessage(pack: GlobalEducationalTechnicalReviewPack): string { return pack.educational_first_contact_message; }
export function renderTechnicalFeedbackInvitation(pack: GlobalEducationalTechnicalReviewPack): string { return pack.technical_feedback_invitation; }
export function renderCommercialPilotFollowUpMessage(pack: GlobalEducationalTechnicalReviewPack): string { return pack.commercial_pilot_follow_up_message; }
export function renderGlobalEducationalTechnicalReviewPackMarkdown(pack: GlobalEducationalTechnicalReviewPack): string { const section = (heading: string, values: readonly string[]) => [`## ${heading}`, ...values.map(value => `- ${value}`), ""]; return ["# Global Educational Technical Review Pack", "", "Draft/local educational material only. Nothing has been sent. No scraping, searching, contact, email, or message has occurred.", "", "## Education-First Positioning", pack.education_first_positioning, "", "## Technical Learning Objective", pack.technical_learning_objective, "", ...section("Who This Is For", pack.target_audience), ...section("Developer Value", pack.developer_value_proposition), ...section("Agent Platform Value", pack.agent_platform_value_proposition), ...section("Governance/Security Value", [...pack.governance_value_proposition, ...pack.security_value_proposition]), "## Quantum-Readiness Positioning", pack.quantum_readiness_statement, "", pack.post_quantum_readiness_statement, "", "No quantum-security or post-quantum-compliance claim is made.", "", "## Educational First-Contact Message", pack.educational_first_contact_message, "", "## Technical Feedback Invitation", pack.technical_feedback_invitation, "", "## Commercial Pilot Follow-Up", pack.commercial_pilot_follow_up_message, "", "## Agent-Readable Review JSON Summary", `- Review type: ${pack.agent_readable_review_json.review_type}`, `- Quantum claim level: ${pack.quantum_claim_level}`, "", ...section("Global Contact Caution Notes", pack.global_contact_caution_notes), "## Opt-Out Wording Draft", pack.opt_out_wording_draft, "", ...section("What Remains Disabled", pack.what_remains_disabled), "## Gareth Approval Gate", "Gareth must manually approve every target and every message before anything is sent or shared.", "", ...section("Recommended Next Steps", pack.recommended_next_steps), "No public API, live agents, payment, billing, settlement, tracking, analytics, deployment, publishing, or action execution is enabled. No legal, compliance, audit, quantum-security, or post-quantum certification is claimed."].join("\n"); }
function safeId(value: string): string { return "source_" + createHash("sha256").update(value, "utf8").digest("hex").slice(0, 20); }
function safeTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "1970-01-01T00:00:00.000Z" : date.toISOString(); }
