import { readFileSync } from "node:fs";
import { createGlobalEducationalTechnicalReviewPack, renderCommercialPilotFollowUpMessage, renderEducationalFirstContactMessage, renderGlobalEducationalTechnicalReviewJson, renderGlobalEducationalTechnicalReviewPackMarkdown, renderTechnicalFeedbackInvitation, type GlobalEducationalTechnicalReviewPackInput } from "./global-educational-technical-review-pack.js";
export type GlobalEducationalReviewCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "REVIEW_PACK_ERROR";
export interface GlobalEducationalReviewCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: GlobalEducationalReviewCliErrorCode, message: string) { super(message); } }
const defaultIo: GlobalEducationalReviewCliIo = { stdout: console.log, stderr: console.error };
export function runGlobalEducationalTechnicalReviewPackCli(args: readonly string[], io: GlobalEducationalReviewCliIo = defaultIo): number { try { const options = parse(args); const pack = createGlobalEducationalTechnicalReviewPack(readGlobalEducationalTechnicalReviewPackInput(options.path)); const output = options.mode === "markdown" ? renderGlobalEducationalTechnicalReviewPackMarkdown(pack) : options.mode === "review-json" ? renderGlobalEducationalTechnicalReviewJson(pack) : options.mode === "first-contact" ? renderEducationalFirstContactMessage(pack) : options.mode === "technical-invite" ? renderTechnicalFeedbackInvitation(pack) : options.mode === "pilot-follow-up" ? renderCommercialPilotFollowUpMessage(pack) : JSON.stringify(pack, null, options.pretty ? 2 : 0); io.stdout(output); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readGlobalEducationalTechnicalReviewPackInput(path: string): GlobalEducationalTechnicalReviewPackInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local educational-review input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local educational-review input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const record = value as Record<string, unknown>; if (typeof record.offer_pack_result !== "object" || record.offer_pack_result === null || Array.isArray(record.offer_pack_result)) throw invalid("Missing offer_pack_result."); if (typeof record.target_list_result !== "object" || record.target_list_result === null || Array.isArray(record.target_list_result)) throw invalid("Missing target_list_result."); if (typeof record.source_id !== "string" || typeof record.created_at !== "string") throw invalid("Missing required local metadata."); return record as unknown as GlobalEducationalTechnicalReviewPackInput; }
function parse(args: readonly string[]) { let path: string | undefined; let pretty = false; let mode: "json" | "markdown" | "review-json" | "first-contact" | "technical-invite" | "pilot-follow-up" = "json"; let selected = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = arg === "--markdown" ? "markdown" : arg === "--review-json" ? "review-json" : arg === "--first-contact" ? "first-contact" : arg === "--technical-invite" ? "technical-invite" : arg === "--pilot-follow-up" ? "pilot-follow-up" : undefined; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported educational-review option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "REVIEW_PACK_ERROR", message: known ? error.message : "The local educational review pack could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, tracking_triggered: false, analytics_triggered: false, payment_or_fee_triggered: false, billing_triggered: false, settlement_triggered: false, machine_to_machine_fee_triggered: false, action_executed: false, email_sent: false, message_sent: false, scraped: false, deployed: false, published: false, manual_contact_only: true, no_automatic_outreach: true, no_scraping_performed: true, no_external_lookup_performed: true, status: "educational_review_pack_only" }; }
if (process.argv[1]?.endsWith("global-educational-technical-review-pack-cli.js")) process.exitCode = runGlobalEducationalTechnicalReviewPackCli(process.argv.slice(2));
