import { readFileSync } from "node:fs";
import { createGlobalDiscoveryVerificationRecord, renderGlobalDiscoveryPostLaunchChecklistMarkdown, renderGlobalDiscoveryVerificationJson, renderGlobalDiscoveryVerificationMarkdown, type GlobalDiscoveryVerificationRecordInput } from "./global-discovery-verification-record.js";
export type GlobalDiscoveryVerificationCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "VERIFICATION_ERROR";
export interface GlobalDiscoveryVerificationCliIo { stdout: (value: string) => void; stderr: (value: string) => void }
class CliError extends Error { constructor(readonly code: GlobalDiscoveryVerificationCliErrorCode, message: string) { super(message); } }
const defaultIo: GlobalDiscoveryVerificationCliIo = { stdout: console.log, stderr: console.error };
export function runGlobalDiscoveryVerificationRecordCli(args: readonly string[], io: GlobalDiscoveryVerificationCliIo = defaultIo): number { try { const options = parse(args), record = createGlobalDiscoveryVerificationRecord(readGlobalDiscoveryVerificationRecordInput(options.path)); io.stdout(options.mode === "markdown" ? renderGlobalDiscoveryVerificationMarkdown(record) : options.mode === "verification" ? renderGlobalDiscoveryVerificationJson(record) : options.mode === "checklist" ? renderGlobalDiscoveryPostLaunchChecklistMarkdown(record) : JSON.stringify(record, null, options.pretty ? 2 : 0)); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readGlobalDiscoveryVerificationRecordInput(path: string): GlobalDiscoveryVerificationRecordInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local verification input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local verification input is not valid JSON."); } if (!value || typeof value !== "object" || Array.isArray(value)) throw invalid("Input must be an object."); const r = value as Record<string, unknown>; if (typeof r.live_discovery_url !== "string" || !r.live_discovery_url) throw invalid("Missing live_discovery_url."); if (!Array.isArray(r.verification_observations)) throw invalid("Missing verification_observations."); if (typeof r.source_id !== "string" || typeof r.created_at !== "string") throw invalid("Missing required local metadata."); return r as unknown as GlobalDiscoveryVerificationRecordInput; }
function parse(args: readonly string[]) { let path: string | undefined, pretty = false, mode: "json" | "markdown" | "verification" | "checklist" = "json", selected = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } const next = arg === "--markdown" ? "markdown" : arg === "--verification-json" ? "verification" : arg === "--post-launch-checklist" ? "checklist" : undefined; if (next) { if (selected) throw new CliError("UNEXPECTED_ARGUMENT", "Select one output format."); mode = next; selected = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported verification option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, mode }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "VERIFICATION_ERROR", message: known ? error.message : "The local verification record could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, live_agent_access_enabled: false, backend_required: false, endpoint_created: false, payment_enabled: false, billing_enabled: false, settlement_enabled: false, tracking_enabled: false, analytics_enabled: false, action_execution_enabled: false, deployed_by_tool: false, published_by_tool: false, status: "verification_record_only" }; }
if (process.argv[1]?.endsWith("global-discovery-verification-record-cli.js")) process.exitCode = runGlobalDiscoveryVerificationRecordCli(process.argv.slice(2));
