import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { buildGlobalDiscoveryLaunchFiles, createGlobalDiscoveryLiveLaunchFolder, type GlobalDiscoveryLiveLaunchFolderInput } from "./global-discovery-live-launch-folder.js";
export type GlobalDiscoveryLaunchCliErrorCode = "MISSING_INPUT_FILE" | "INPUT_FILE_UNREADABLE" | "INVALID_JSON" | "INVALID_INPUT" | "UNKNOWN_OPTION" | "UNEXPECTED_ARGUMENT" | "WRITE_ERROR" | "LAUNCH_FOLDER_ERROR";
export interface GlobalDiscoveryLaunchCliIo { stdout: (value: string) => void; stderr: (value: string) => void; cwd?: string }
class CliError extends Error { constructor(readonly code: GlobalDiscoveryLaunchCliErrorCode, message: string) { super(message); } }
const defaultIo: GlobalDiscoveryLaunchCliIo = { stdout: console.log, stderr: console.error };
export function runGlobalDiscoveryLiveLaunchFolderCli(args: readonly string[], io: GlobalDiscoveryLaunchCliIo = defaultIo): number { try { const options = parse(args), input = readGlobalDiscoveryLiveLaunchFolderInput(options.path), result = createGlobalDiscoveryLiveLaunchFolder(input), files = buildGlobalDiscoveryLaunchFiles(input); if (!options.dryRun && !options.listFiles) writeLaunchFiles(files, io.cwd ?? process.cwd()); io.stdout(options.listFiles ? Object.keys(files).join("\n") : JSON.stringify({ ...result, dry_run: options.dryRun, files_written: !options.dryRun && !options.listFiles }, null, options.pretty ? 2 : 0)); return 0; } catch (error) { io.stderr(JSON.stringify(safeError(error), null, 2)); return 1; } }
export function readGlobalDiscoveryLiveLaunchFolderInput(path: string): GlobalDiscoveryLiveLaunchFolderInput { let text: string; try { text = readFileSync(path, "utf8"); } catch { throw new CliError("INPUT_FILE_UNREADABLE", "The local launch-folder input could not be read."); } let value: unknown; try { value = JSON.parse(text); } catch { throw new CliError("INVALID_JSON", "The local launch-folder input is not valid JSON."); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw invalid("Input must be an object."); const record = value as Record<string, unknown>; if (typeof record.agent_to_agent_discovery_pack_result !== "object" || record.agent_to_agent_discovery_pack_result === null || Array.isArray(record.agent_to_agent_discovery_pack_result)) throw invalid("Missing agent_to_agent_discovery_pack_result."); if (typeof record.source_id !== "string" || typeof record.created_at !== "string") throw invalid("Missing required local metadata."); return record as GlobalDiscoveryLiveLaunchFolderInput; }
function writeLaunchFiles(files: Record<string, string>, cwd: string): void { const root = resolve(cwd, "global-discovery-launch"); try { for (const [relative, content] of Object.entries(files)) { const destination = resolve(root, relative); if (destination !== root && !destination.startsWith(root + "\\") && !destination.startsWith(root + "/")) throw new CliError("WRITE_ERROR", "A generated path was outside the launch folder."); mkdirSync(dirname(destination), { recursive: true }); writeFileSync(destination, content, "utf8"); } } catch (error) { if (error instanceof CliError) throw error; throw new CliError("WRITE_ERROR", "The static launch folder could not be written safely."); } }
function parse(args: readonly string[]) { let path: string | undefined, pretty = false, dryRun = false, listFiles = false; for (const arg of args) { if (arg === "--pretty") { pretty = true; continue; } if (arg === "--dry-run") { dryRun = true; continue; } if (arg === "--list-files") { listFiles = true; continue; } if (arg.startsWith("--")) throw new CliError("UNKNOWN_OPTION", "Unsupported launch-folder option."); if (path) throw new CliError("UNEXPECTED_ARGUMENT", "One input file is accepted."); path = arg; } if (!path) throw new CliError("MISSING_INPUT_FILE", "A local JSON input file is required."); return { path, pretty, dryRun, listFiles }; }
function invalid(message: string) { return new CliError("INVALID_INPUT", message); }
function safeError(error: unknown) { const known = error instanceof CliError; return { error: { code: known ? error.code : "LAUNCH_FOLDER_ERROR", message: known ? error.message : "The static launch folder could not complete safely." }, private_data_included: false, network_lookup_performed: false, external_lookup_performed: false, public_api_enabled: false, live_agent_access_enabled: false, backend_required: false, endpoint_created: false, payment_enabled: false, tracking_enabled: false, analytics_enabled: false, action_execution_enabled: false, deployed: false, published: false, status: "launch_folder_only" }; }
if (process.argv[1]?.endsWith("global-discovery-live-launch-folder-cli.js")) process.exitCode = runGlobalDiscoveryLiveLaunchFolderCli(process.argv.slice(2));
