import { createHash } from "node:crypto";
import { runControlledSandboxReadiness, type ControlledSandboxReadinessInput, type SandboxAccessStatus } from "./controlled-sandbox-readiness.js";

export const SANDBOX_END_TO_END_SMOKE_TEST_VERSION = "atg.sandbox-end-to-end-smoke-test.v1" as const;
export type SandboxSmokeScenarioType = "allowed_sandbox_agent" | "denied_sandbox_agent" | "missing_entitlement" | "unknown_local_scenario";
export interface SandboxSmokeScenarioInput extends ControlledSandboxReadinessInput { scenario_type: string }
export interface SandboxEndToEndSmokeTestInput { [key:string]:unknown; smoke_test_id?:string; source_id:string; scenarios:readonly SandboxSmokeScenarioInput[]; created_at:string }
export interface SandboxSmokeScenarioResult { scenario_type:SandboxSmokeScenarioType; sandbox_access_status:SandboxAccessStatus; engine_ran:boolean; approval_required:boolean; uses_consumed:number; hypothetical_revenue_event_count:number; action_executed:false; status:"sandbox_only" }
export interface SandboxEndToEndSmokeTestResult {
 smoke_test_id:string; smoke_test_type:"controlled_sandbox_end_to_end_smoke_test"; source_id:string; scenario_count:number; allowed_sandbox_agent_passed:boolean; denied_sandbox_agent_blocked:boolean; missing_entitlement_blocked:boolean; engine_ran_count:number; engine_denied_count:number; placeholder_uses_consumed:number; approval_required_count:number; hypothetical_revenue_event_count:number; smoke_test_passed:boolean; failure_reasons:string[]; smoke_test_summary:string; plain_english_result:string; recommended_next_steps:string[]; scenario_results:SandboxSmokeScenarioResult[]; private_data_included:false; network_lookup_performed:false; external_lookup_performed:false; public_api_enabled:false; tracking_triggered:false; analytics_triggered:false; payment_or_fee_triggered:false; billing_triggered:false; settlement_triggered:false; machine_to_machine_fee_triggered:false; action_executed:false; deployed:false; published:false; status:"sandbox_only"; created_at:string;
}
export type SandboxEndToEndSmokeTestSummary=Omit<SandboxEndToEndSmokeTestResult,"scenario_results"|"recommended_next_steps"|"created_at">;

export function runSandboxEndToEndSmokeTest(input:SandboxEndToEndSmokeTestInput):SandboxEndToEndSmokeTestResult {
 const rows=(Array.isArray(input.scenarios)?input.scenarios:[]).map(runScenario);
 const allowed=rows.some(r=>r.scenario_type==="allowed_sandbox_agent"&&r.sandbox_access_status==="sandbox_clearing_allowed"&&r.engine_ran);
 const denied=rows.some(r=>r.scenario_type==="denied_sandbox_agent"&&r.sandbox_access_status==="agent_not_allowlisted"&&!r.engine_ran);
 const missing=rows.some(r=>r.scenario_type==="missing_entitlement"&&r.sandbox_access_status==="sandbox_entitlement_required"&&!r.engine_ran);
 const failures:string[]=[]; if(!allowed)failures.push("allowed_sandbox_agent_check_failed");if(!denied)failures.push("denied_sandbox_agent_check_failed");if(!missing)failures.push("missing_entitlement_check_failed");if(rows.length!==3)failures.push("expected_three_scenarios");if(rows.some(r=>r.action_executed))failures.push("action_execution_detected");
 const passed=failures.length===0;
 return { smoke_test_id:createSandboxSmokeTestId(input.smoke_test_id??input.source_id), smoke_test_type:"controlled_sandbox_end_to_end_smoke_test", source_id:safeId(input.source_id), scenario_count:rows.length, allowed_sandbox_agent_passed:allowed, denied_sandbox_agent_blocked:denied, missing_entitlement_blocked:missing, engine_ran_count:rows.filter(r=>r.engine_ran).length, engine_denied_count:rows.filter(r=>!r.engine_ran).length, placeholder_uses_consumed:sum(rows.map(r=>r.uses_consumed)), approval_required_count:rows.filter(r=>r.approval_required).length, hypothetical_revenue_event_count:sum(rows.map(r=>r.hypothetical_revenue_event_count)), smoke_test_passed:passed, failure_reasons:failures, smoke_test_summary:passed?"All three controlled sandbox readiness checks passed locally.":`Sandbox smoke test failed: ${failures.join(", ")}.`, plain_english_result:passed?"Sandbox smoke test passed. Allowlisted entitled sandbox agent ran the local clearing engine. Non-allowlisted agent was denied. Missing-entitlement agent was denied. No network, public API, billing, payment, settlement, tracking, analytics, deployment, publishing, or action execution occurred.":"Sandbox smoke test did not pass every required local check. No live capability or action was activated.", recommended_next_steps:passed?["retain_sandbox_only_controls","require_gareth_approval_before_live_testing"]:["review_failure_reasons","keep_all_live_capabilities_disabled"], scenario_results:rows, private_data_included:false, network_lookup_performed:false, external_lookup_performed:false, public_api_enabled:false, tracking_triggered:false, analytics_triggered:false, payment_or_fee_triggered:false, billing_triggered:false, settlement_triggered:false, machine_to_machine_fee_triggered:false, action_executed:false, deployed:false, published:false, status:"sandbox_only", created_at:safeTimestamp(input.created_at) };
}
export function createSandboxSmokeTestId(sourceId:string):string{return "sandbox_smoke_test_"+createHash("sha256").update(sourceId,"utf8").digest("hex").slice(0,24);}
export function summariseSandboxEndToEndSmokeTest(result:SandboxEndToEndSmokeTestResult):SandboxEndToEndSmokeTestSummary{const{scenario_results:_r,recommended_next_steps:_n,created_at:_c,...summary}=result;return summary;}
function runScenario(input:SandboxSmokeScenarioInput):SandboxSmokeScenarioResult{const result=runControlledSandboxReadiness(input);return{scenario_type:safeType(input.scenario_type),sandbox_access_status:result.sandbox_access_status,engine_ran:result.engine_run_id!==null,approval_required:result.approval_required,uses_consumed:result.uses_consumed,hypothetical_revenue_event_count:result.hypothetical_revenue_event_count,action_executed:false,status:"sandbox_only"};}
function safeType(v:string):SandboxSmokeScenarioType{return v==="allowed_sandbox_agent"||v==="denied_sandbox_agent"||v==="missing_entitlement"?v:"unknown_local_scenario";}
function sum(v:readonly number[]):number{return v.reduce((a,b)=>a+b,0)}
function safeId(v:string):string{return "source_"+createHash("sha256").update(v,"utf8").digest("hex").slice(0,20)}
function safeTimestamp(v:string):string{const d=new Date(v);return Number.isNaN(d.valueOf())?"1970-01-01T00:00:00.000Z":d.toISOString()}
